const COUNTRY_IQ_DATA = {
  "Afghanistan": { avg: 84, continent: "Asia" },
  "Albania": { avg: 90, continent: "Europe" },
  "Algeria": { avg: 83, continent: "Africa" },
  "Argentina": { avg: 93, continent: "South America" },
  "Armenia": { avg: 94, continent: "Europe" },
  "Australia": { avg: 99, continent: "Oceania" },
  "Austria": { avg: 100, continent: "Europe" },
  "Azerbaijan": { avg: 88, continent: "Asia" },
  "Bangladesh": { avg: 82, continent: "Asia" },
  "Belarus": { avg: 97, continent: "Europe" },
  "Belgium": { avg: 99, continent: "Europe" },
  "Bolivia": { avg: 87, continent: "South America" },
  "Bosnia and Herzegovina": { avg: 93, continent: "Europe" },
  "Brazil": { avg: 87, continent: "South America" },
  "Bulgaria": { avg: 93, continent: "Europe" },
  "Cambodia": { avg: 92, continent: "Asia" },
  "Cameroon": { avg: 70, continent: "Africa" },
  "Canada": { avg: 101, continent: "North America" },
  "Chile": { avg: 90, continent: "South America" },
  "China": { avg: 105, continent: "Asia" },
  "Colombia": { avg: 89, continent: "South America" },
  "Costa Rica": { avg: 89, continent: "North America" },
  "Croatia": { avg: 98, continent: "Europe" },
  "Cuba": { avg: 89, continent: "North America" },
  "Cyprus": { avg: 92, continent: "Europe" },
  "Czech Republic": { avg: 98, continent: "Europe" },
  "Denmark": { avg: 99, continent: "Europe" },
  "Dominican Republic": { avg: 84, continent: "North America" },
  "Ecuador": { avg: 88, continent: "South America" },
  "Egypt": { avg: 83, continent: "Africa" },
  "El Salvador": { avg: 84, continent: "North America" },
  "Estonia": { avg: 100, continent: "Europe" },
  "Ethiopia": { avg: 69, continent: "Africa" },
  "Finland": { avg: 101, continent: "Europe" },
  "France": { avg: 98, continent: "Europe" },
  "Georgia": { avg: 92, continent: "Europe" },
  "Germany": { avg: 100, continent: "Europe" },
  "Ghana": { avg: 73, continent: "Africa" },
  "Greece": { avg: 93, continent: "Europe" },
  "Guatemala": { avg: 79, continent: "North America" },
  "Honduras": { avg: 81, continent: "North America" },
  "Hungary": { avg: 99, continent: "Europe" },
  "Iceland": { avg: 101, continent: "Europe" },
  "India": { avg: 82, continent: "Asia" },
  "Indonesia": { avg: 87, continent: "Asia" },
  "Iran": { avg: 84, continent: "Asia" },
  "Iraq": { avg: 87, continent: "Asia" },
  "Ireland": { avg: 100, continent: "Europe" },
  "Israel": { avg: 95, continent: "Asia" },
  "Italy": { avg: 97, continent: "Europe" },
  "Jamaica": { avg: 71, continent: "North America" },
  "Japan": { avg: 106, continent: "Asia" },
  "Jordan": { avg: 84, continent: "Asia" },
  "Kazakhstan": { avg: 94, continent: "Asia" },
  "Kenya": { avg: 80, continent: "Africa" },
  "Kuwait": { avg: 86, continent: "Asia" },
  "Latvia": { avg: 97, continent: "Europe" },
  "Lebanon": { avg: 82, continent: "Asia" },
  "Libya": { avg: 84, continent: "Africa" },
  "Lithuania": { avg: 97, continent: "Europe" },
  "Luxembourg": { avg: 100, continent: "Europe" },
  "Malaysia": { avg: 93, continent: "Asia" },
  "Mexico": { avg: 88, continent: "North America" },
  "Moldova": { avg: 92, continent: "Europe" },
  "Mongolia": { avg: 100, continent: "Asia" },
  "Montenegro": { avg: 90, continent: "Europe" },
  "Morocco": { avg: 84, continent: "Africa" },
  "Mozambique": { avg: 72, continent: "Africa" },
  "Myanmar": { avg: 85, continent: "Asia" },
  "Nepal": { avg: 78, continent: "Asia" },
  "Netherlands": { avg: 100, continent: "Europe" },
  "New Zealand": { avg: 99, continent: "Oceania" },
  "Nicaragua": { avg: 81, continent: "North America" },
  "Nigeria": { avg: 71, continent: "Africa" },
  "North Korea": { avg: 102, continent: "Asia" },
  "North Macedonia": { avg: 91, continent: "Europe" },
  "Norway": { avg: 100, continent: "Europe" },
  "Pakistan": { avg: 84, continent: "Asia" },
  "Panama": { avg: 84, continent: "North America" },
  "Paraguay": { avg: 84, continent: "South America" },
  "Peru": { avg: 89, continent: "South America" },
  "Philippines": { avg: 86, continent: "Asia" },
  "Poland": { avg: 99, continent: "Europe" },
  "Portugal": { avg: 95, continent: "Europe" },
  "Qatar": { avg: 78, continent: "Asia" },
  "Romania": { avg: 94, continent: "Europe" },
  "Russia": { avg: 97, continent: "Europe" },
  "Saudi Arabia": { avg: 84, continent: "Asia" },
  "Senegal": { avg: 76, continent: "Africa" },
  "Serbia": { avg: 92, continent: "Europe" },
  "Singapore": { avg: 108, continent: "Asia" },
  "Slovakia": { avg: 98, continent: "Europe" },
  "Slovenia": { avg: 98, continent: "Europe" },
  "South Africa": { avg: 77, continent: "Africa" },
  "South Korea": { avg: 106, continent: "Asia" },
  "Spain": { avg: 97, continent: "Europe" },
  "Sri Lanka": { avg: 79, continent: "Asia" },
  "Sudan": { avg: 71, continent: "Africa" },
  "Sweden": { avg: 99, continent: "Europe" },
  "Switzerland": { avg: 101, continent: "Europe" },
  "Syria": { avg: 83, continent: "Asia" },
  "Taiwan": { avg: 106, continent: "Asia" },
  "Tanzania": { avg: 72, continent: "Africa" },
  "Thailand": { avg: 91, continent: "Asia" },
  "Tunisia": { avg: 84, continent: "Africa" },
  "Turkey": { avg: 90, continent: "Europe" },
  "Uganda": { avg: 73, continent: "Africa" },
  "Ukraine": { avg: 97, continent: "Europe" },
  "United Arab Emirates": { avg: 84, continent: "Asia" },
  "United Kingdom": { avg: 100, continent: "Europe" },
  "United States": { avg: 98, continent: "North America" },
  "Uruguay": { avg: 96, continent: "South America" },
  "Uzbekistan": { avg: 87, continent: "Asia" },
  "Venezuela": { avg: 84, continent: "South America" },
  "Vietnam": { avg: 94, continent: "Asia" },
  "Zimbabwe": { avg: 72, continent: "Africa" }
};

const REGIONAL_AVERAGES = {
  "Europe": 96,
  "Asia": 91,
  "North America": 94,
  "South America": 88,
  "Africa": 75,
  "Oceania": 99,
  "World": 89
};
