// ============================================================================
// AGE 8–11: Mix of visual puzzles and simple numerical questions.
//           Number grids, multiplication patterns, basic syllogisms, 3D shapes.
//           130 questions (26 per category), test uses selected per category
// ============================================================================
const QUESTIONS_AGE_8_11 = [

  // =========================================================================
  // PATTERN RECOGNITION (26 questions: Y2PR1 – Y2PR26)
  // =========================================================================

  { id: "Y2PR1", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 2, 3], [4, 5, 6], [7, 8, "?"]],
    options: ["9", "10", "11", "7"], correct: 0,
    explanation: "Counting from 1 to 9, left to right, top to bottom. The missing number is 9." },
  { id: "Y2PR2", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next in the sequence?",
    visual: "sequence", sequence: ["□", "□■", "□■□", "?"],
    options: ["□■□■", "■□■□", "□□□□", "■■■■"], correct: 0,
    explanation: "The pattern alternates □ and ■, adding one each step. Next: □■□■." },
  { id: "Y2PR3", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 4, 6], [8, 10, 12], [14, 16, "?"]],
    options: ["18", "17", "20", "15"], correct: 0,
    explanation: "These are even numbers in order: 2, 4, 6, 8, 10, 12, 14, 16, 18." },
  { id: "Y2PR4", category: "Pattern Recognition", difficulty: 2,
    question: "What comes next?",
    visual: "sequence", sequence: ["★", "★☆", "★☆★", "?"],
    options: ["★☆★☆", "☆★☆★", "★★★★", "☆☆☆☆"], correct: 0,
    explanation: "Alternating filled and empty stars, growing by one each step. Next: ★☆★☆." },
  { id: "Y2PR5", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[3, 6, 9], [12, 15, 18], [21, 24, "?"]],
    options: ["27", "25", "30", "26"], correct: 0,
    explanation: "These are multiples of 3 in order. After 24 comes 27." },
  { id: "Y2PR6", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[5, 10, 15], [20, 25, 30], [35, 40, "?"]],
    options: ["45", "50", "42", "44"], correct: 0,
    explanation: "These are multiples of 5 in order. After 40 comes 45." },
  { id: "Y2PR7", category: "Pattern Recognition", difficulty: 2,
    question: "Identify the rule and find the missing element.",
    visual: "number-grid", grid: [[2, 4, 6], [3, 6, 9], [5, 10, "?"]],
    options: ["15", "20", "12", "25"], correct: 0,
    explanation: "Each row is multiples of the first number: 5×1, 5×2, 5×3 = 15." },
  { id: "Y2PR8", category: "Pattern Recognition", difficulty: 2,
    question: "What comes next?",
    visual: "sequence", sequence: ["▲▼", "▲▼▲", "▲▼▲▼", "?"],
    options: ["▲▼▲▼▲", "▼▲▼▲▼", "▲▲▲▲▲", "▼▼▼▼▼"], correct: 0,
    explanation: "Alternating up and down triangles, growing by one each step. Next: ▲▼▲▼▲." },

  { id: "Y2PR9", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[4, 8, 12], [16, 20, 24], [28, 32, "?"]],
    options: ["36", "34", "40", "30"], correct: 0,
    explanation: "These are multiples of 4 in order. After 32 comes 36." },
  { id: "Y2PR10", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next in the sequence?",
    visual: "sequence", sequence: ["○", "○●", "○●○", "?"],
    options: ["○●○●", "●○●○", "○○○○", "●●●●"], correct: 0,
    explanation: "The pattern alternates ○ and ●, adding one each step. Next: ○●○●." },
  { id: "Y2PR11", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[7, 14, 21], [28, 35, 42], [49, 56, "?"]],
    options: ["63", "64", "70", "60"], correct: 0,
    explanation: "These are multiples of 7 in order. After 56 comes 63." },
  { id: "Y2PR12", category: "Pattern Recognition", difficulty: 2,
    question: "Identify the rule and find the missing number.",
    visual: "number-grid", grid: [[4, 8, 12], [6, 12, 18], [7, 14, "?"]],
    options: ["21", "28", "18", "24"], correct: 0,
    explanation: "Each row shows the first number ×1, ×2, ×3. So 7 × 3 = 21." },
  { id: "Y2PR13", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next?",
    visual: "sequence", sequence: ["◆", "◆◇", "◆◇◆", "?"],
    options: ["◆◇◆◇", "◇◆◇◆", "◆◆◆◆", "◇◇◇◇"], correct: 0,
    explanation: "Alternating ◆ and ◇, growing by one each step. Next: ◆◇◆◇." },
  { id: "Y2PR14", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[6, 12, 18], [24, 30, 36], [42, 48, "?"]],
    options: ["54", "56", "60", "50"], correct: 0,
    explanation: "These are multiples of 6 in order. After 48 comes 54." },
  { id: "Y2PR15", category: "Pattern Recognition", difficulty: 2,
    question: "Identify the rule and find the missing number.",
    visual: "number-grid", grid: [[1, 2, 4], [3, 6, 12], [5, 10, "?"]],
    options: ["20", "15", "25", "10"], correct: 0,
    explanation: "Each row: col2 = col1 × 2, col3 = col1 × 4. So 5 × 4 = 20." },
  { id: "Y2PR16", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next?",
    visual: "sequence", sequence: ["♠", "♠♣", "♠♣♠", "?"],
    options: ["♠♣♠♣", "♣♠♣♠", "♠♠♠♠", "♣♣♣♣"], correct: 0,
    explanation: "Alternating ♠ and ♣, growing by one each step. Next: ♠♣♠♣." },
  { id: "Y2PR17", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[8, 16, 24], [32, 40, 48], [56, 64, "?"]],
    options: ["72", "68", "80", "70"], correct: 0,
    explanation: "These are multiples of 8 in order. After 64 comes 72." },
  { id: "Y2PR18", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[9, 18, 27], [36, 45, 54], [63, 72, "?"]],
    options: ["81", "80", "90", "78"], correct: 0,
    explanation: "These are multiples of 9 in order. After 72 comes 81." },
  { id: "Y2PR19", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[10, 15, 20], [25, 30, 35], [40, 45, "?"]],
    options: ["50", "55", "48", "52"], correct: 0,
    explanation: "Numbers increase by 5 each step, starting at 10. After 45 comes 50." },
  { id: "Y2PR20", category: "Pattern Recognition", difficulty: 2,
    question: "What comes next?",
    visual: "sequence", sequence: ["▶", "▶◀", "▶◀▶", "?"],
    options: ["▶◀▶◀", "◀▶◀▶", "▶▶▶▶", "◀◀◀◀"], correct: 0,
    explanation: "Alternating ▶ and ◀, growing by one each step. Next: ▶◀▶◀." },
  { id: "Y2PR21", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[11, 22, 33], [44, 55, 66], [77, 88, "?"]],
    options: ["99", "100", "110", "96"], correct: 0,
    explanation: "These are multiples of 11 in order. After 88 comes 99." },
  { id: "Y2PR22", category: "Pattern Recognition", difficulty: 2,
    question: "Identify the rule and find the missing number.",
    visual: "number-grid", grid: [[2, 6, 10], [4, 12, 20], [3, 9, "?"]],
    options: ["15", "12", "18", "21"], correct: 0,
    explanation: "Each row: col2 = col1 × 3, col3 = col1 × 5. So 3 × 5 = 15." },
  { id: "Y2PR23", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[12, 24, 36], [48, 60, 72], [84, 96, "?"]],
    options: ["108", "100", "110", "104"], correct: 0,
    explanation: "These are multiples of 12 in order. After 96 comes 108." },
  { id: "Y2PR24", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 4, 7], [10, 13, 16], [19, 22, "?"]],
    options: ["25", "24", "27", "23"], correct: 0,
    explanation: "Each number increases by 3. After 22 comes 25." },
  { id: "Y2PR25", category: "Pattern Recognition", difficulty: 2,
    question: "What comes next?",
    visual: "sequence", sequence: ["●○", "●○●", "●○●○", "?"],
    options: ["●○●○●", "○●○●○", "●●●●●", "○○○○○"], correct: 0,
    explanation: "Alternating ● and ○, growing by one each step. Next: ●○●○●." },
  { id: "Y2PR26", category: "Pattern Recognition", difficulty: 2,
    question: "Identify the rule and find the missing number.",
    visual: "number-grid", grid: [[3, 6, 12], [2, 4, 8], [5, 10, "?"]],
    options: ["20", "25", "15", "30"], correct: 0,
    explanation: "Each row: col2 = col1 × 2, col3 = col1 × 4. So 5 × 4 = 20." },

  // =========================================================================
  // NUMERICAL REASONING (26 questions: Y2NR1 – Y2NR26)
  // =========================================================================

  { id: "Y2NR1", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [3, 6, 9, 12, 15, "?"],
    options: ["18", "17", "21", "16"], correct: 0,
    explanation: "Each number increases by 3 (the 3 times table). 15 + 3 = 18." },
  { id: "Y2NR2", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [100, 90, 80, 70, "?"],
    options: ["60", "65", "50", "75"], correct: 0,
    explanation: "Each number decreases by 10. 70 − 10 = 60." },
  { id: "Y2NR3", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [4, 8, 12, 16, 20, "?"],
    options: ["24", "22", "28", "26"], correct: 0,
    explanation: "Each number increases by 4. 20 + 4 = 24." },
  { id: "Y2NR4", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 4, 8, 16, "?"],
    options: ["32", "24", "20", "64"], correct: 0,
    explanation: "Each number doubles. 16 × 2 = 32." },
  { id: "Y2NR5", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 3, 9, 27, 81, "?"],
    options: ["243", "162", "100", "200"], correct: 0,
    explanation: "Each number is tripled. 81 × 3 = 243." },
  { id: "Y2NR6", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [50, 45, 40, 35, 30, "?"],
    options: ["25", "20", "28", "35"], correct: 0,
    explanation: "Each number decreases by 5. 30 − 5 = 25." },
  { id: "Y2NR7", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [7, 14, 21, 28, 35, "?"],
    options: ["42", "40", "49", "38"], correct: 0,
    explanation: "Each number increases by 7 (the 7 times table). 35 + 7 = 42." },
  { id: "Y2NR8", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 4, 7, 10, 13, "?"],
    options: ["16", "15", "17", "14"], correct: 0,
    explanation: "Each number increases by 3. 13 + 3 = 16." },

  { id: "Y2NR9", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [6, 12, 18, 24, 30, "?"],
    options: ["36", "32", "42", "34"], correct: 0,
    explanation: "Each number increases by 6 (the 6 times table). 30 + 6 = 36." },
  { id: "Y2NR10", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [8, 16, 24, 32, 40, "?"],
    options: ["48", "44", "50", "46"], correct: 0,
    explanation: "Each number increases by 8 (the 8 times table). 40 + 8 = 48." },
  { id: "Y2NR11", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [9, 18, 27, 36, 45, "?"],
    options: ["54", "56", "63", "50"], correct: 0,
    explanation: "Each number increases by 9 (the 9 times table). 45 + 9 = 54." },
  { id: "Y2NR12", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [11, 22, 33, 44, 55, "?"],
    options: ["66", "60", "77", "64"], correct: 0,
    explanation: "Each number increases by 11 (the 11 times table). 55 + 11 = 66." },
  { id: "Y2NR13", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [12, 24, 36, 48, 60, "?"],
    options: ["72", "68", "84", "70"], correct: 0,
    explanation: "Each number increases by 12 (the 12 times table). 60 + 12 = 72." },
  { id: "Y2NR14", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [3, 6, 12, 24, 48, "?"],
    options: ["96", "72", "84", "100"], correct: 0,
    explanation: "Each number doubles. 48 × 2 = 96." },
  { id: "Y2NR15", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [96, 48, 24, 12, "?"],
    options: ["6", "8", "3", "10"], correct: 0,
    explanation: "Each number is halved. 12 ÷ 2 = 6." },
  { id: "Y2NR16", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [64, 32, 16, 8, "?"],
    options: ["4", "2", "6", "0"], correct: 0,
    explanation: "Each number is halved. 8 ÷ 2 = 4." },
  { id: "Y2NR17", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [200, 180, 160, 140, "?"],
    options: ["120", "130", "100", "110"], correct: 0,
    explanation: "Each number decreases by 20. 140 − 20 = 120." },
  { id: "Y2NR18", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [5, 10, 20, 40, 80, "?"],
    options: ["160", "120", "100", "200"], correct: 0,
    explanation: "Each number doubles. 80 × 2 = 160." },
  { id: "Y2NR19", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [99, 88, 77, 66, "?"],
    options: ["55", "56", "44", "50"], correct: 0,
    explanation: "Each number decreases by 11. 66 − 11 = 55." },
  { id: "Y2NR20", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [15, 25, 35, 45, 55, "?"],
    options: ["65", "60", "70", "55"], correct: 0,
    explanation: "Each number increases by 10. 55 + 10 = 65." },
  { id: "Y2NR21", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [100, 91, 82, 73, "?"],
    options: ["64", "62", "66", "60"], correct: 0,
    explanation: "Each number decreases by 9. 73 − 9 = 64." },
  { id: "Y2NR22", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 6, 18, 54, "?"],
    options: ["162", "108", "148", "180"], correct: 0,
    explanation: "Each number is tripled. 54 × 3 = 162." },
  { id: "Y2NR23", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [128, 64, 32, 16, "?"],
    options: ["8", "4", "12", "10"], correct: 0,
    explanation: "Each number is halved. 16 ÷ 2 = 8." },
  { id: "Y2NR24", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [25, 50, 75, 100, "?"],
    options: ["125", "120", "150", "110"], correct: 0,
    explanation: "Each number increases by 25. 100 + 25 = 125." },
  { id: "Y2NR25", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 4, 7, 11, "?"],
    options: ["16", "15", "14", "17"], correct: 0,
    explanation: "The differences increase by 1 each time: +1, +2, +3, +4, +5. So 11 + 5 = 16." },
  { id: "Y2NR26", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [10, 21, 32, 43, 54, "?"],
    options: ["65", "60", "66", "63"], correct: 0,
    explanation: "Each number increases by 11. 54 + 11 = 65." },

  // =========================================================================
  // LOGICAL REASONING (26 questions: Y2LR1 – Y2LR26)
  // =========================================================================

  { id: "Y2LR1", category: "Logical Reasoning", difficulty: 1,
    question: "If it is raining, the grass is wet. The grass is wet. What can you say?",
    visual: "text",
    options: ["It might be raining, but there could be another reason", "It is definitely raining", "It is not raining", "The grass is always wet"],
    correct: 0,
    explanation: "The grass being wet doesn't mean it must be raining — someone could have used a hose." },
  { id: "Y2LR2", category: "Logical Reasoning", difficulty: 1,
    question: "Alice is older than Ben. Ben is older than Charlie. Charlie is older than Diana. Who is the oldest?",
    visual: "text",
    options: ["Alice", "Ben", "Charlie", "Diana"], correct: 0,
    explanation: "Alice > Ben > Charlie > Diana. Alice is the oldest." },
  { id: "Y2LR3", category: "Logical Reasoning", difficulty: 1,
    question: "All chocolate is sweet. This candy is sweet. Is this candy chocolate?",
    visual: "text",
    options: ["Not necessarily — other things can be sweet too", "Yes, it must be", "No, it can't be", "We need more information"],
    correct: 0,
    explanation: "Just because all chocolate is sweet doesn't mean everything sweet is chocolate." },
  { id: "Y2LR4", category: "Logical Reasoning", difficulty: 2,
    question: "All dogs are animals. All animals need water. Therefore:",
    visual: "text",
    options: ["All dogs need water", "All animals are dogs", "Some dogs don't need water", "Water needs dogs"],
    correct: 0,
    explanation: "By transitive logic: dogs are animals, animals need water, so all dogs need water." },
  { id: "Y2LR5", category: "Logical Reasoning", difficulty: 2,
    question: "No fish can fly. A salmon is a fish. Therefore:",
    visual: "text",
    options: ["A salmon cannot fly", "A salmon can swim", "All fish are salmon", "Some fish can fly"],
    correct: 0,
    explanation: "If no fish can fly and a salmon is a fish, then a salmon cannot fly." },
  { id: "Y2LR6", category: "Logical Reasoning", difficulty: 2,
    question: "A is taller than B. C is shorter than B. Who is the shortest?",
    visual: "text",
    options: ["C", "B", "A", "Cannot tell"], correct: 0,
    explanation: "A > B > C. C is the shortest." },
  { id: "Y2LR7", category: "Logical Reasoning", difficulty: 2,
    question: "All cats are mammals. All mammals are warm-blooded. Therefore:",
    visual: "text",
    options: ["All cats are warm-blooded", "All warm-blooded animals are cats", "Some cats are cold-blooded", "No mammals are cats"],
    correct: 0,
    explanation: "Cats are mammals, mammals are warm-blooded, so all cats are warm-blooded." },
  { id: "Y2LR8", category: "Logical Reasoning", difficulty: 2,
    question: "If every student passed the exam, and John is a student, what can you conclude?",
    visual: "text",
    options: ["John passed the exam", "John studied hard", "The exam was easy", "Everyone is a student"],
    correct: 0,
    explanation: "If every student passed and John is a student, then John passed the exam." },

  { id: "Y2LR9", category: "Logical Reasoning", difficulty: 1,
    question: "All squares have 4 sides. This shape has 4 sides. Is it definitely a square?",
    visual: "text",
    options: ["No — rectangles and other shapes also have 4 sides", "Yes, it must be a square", "It has 5 sides", "Shapes cannot have 4 sides"],
    correct: 0,
    explanation: "Having 4 sides doesn't make a shape a square. Rectangles, rhombuses, and trapezoids also have 4 sides." },
  { id: "Y2LR10", category: "Logical Reasoning", difficulty: 1,
    question: "Amy is faster than Ben. Ben is faster than Chris. Chris is faster than Dan. Who is the slowest?",
    visual: "text",
    options: ["Dan", "Chris", "Ben", "Amy"], correct: 0,
    explanation: "Amy > Ben > Chris > Dan in speed. Dan is the slowest." },
  { id: "Y2LR11", category: "Logical Reasoning", difficulty: 1,
    question: "What day comes 3 days after Wednesday?",
    visual: "text",
    options: ["Saturday", "Sunday", "Friday", "Thursday"], correct: 0,
    explanation: "Wednesday → Thursday (1) → Friday (2) → Saturday (3)." },
  { id: "Y2LR12", category: "Logical Reasoning", difficulty: 1,
    question: "If it snows, school is closed. It snowed today. What can you conclude?",
    visual: "text",
    options: ["School is closed today", "It is cold outside", "Children are playing", "The sun is shining"],
    correct: 0,
    explanation: "The rule says if it snows then school is closed. It snowed, so school is closed." },
  { id: "Y2LR13", category: "Logical Reasoning", difficulty: 2,
    question: "All roses are flowers. This plant is a flower. Is it necessarily a rose?",
    visual: "text",
    options: ["Not necessarily — many other plants are flowers too", "Yes, it must be a rose", "No flowers are roses", "Roses are not plants"],
    correct: 0,
    explanation: "All roses are flowers, but not all flowers are roses. It could be a daisy, tulip, etc." },
  { id: "Y2LR14", category: "Logical Reasoning", difficulty: 2,
    question: "Eve is taller than Fay. Fay is taller than Grace. Grace is taller than Hana. Hana is taller than Ivy. Who is in the middle?",
    visual: "text",
    options: ["Grace", "Fay", "Hana", "Eve"], correct: 0,
    explanation: "Eve > Fay > Grace > Hana > Ivy. Grace is 3rd out of 5, so she is in the middle." },
  { id: "Y2LR15", category: "Logical Reasoning", difficulty: 1,
    question: "What month comes 2 months after October?",
    visual: "text",
    options: ["December", "November", "January", "September"], correct: 0,
    explanation: "October → November (1) → December (2)." },
  { id: "Y2LR16", category: "Logical Reasoning", difficulty: 1,
    question: "All mammals breathe air. Dolphins are mammals. Therefore:",
    visual: "text",
    options: ["Dolphins breathe air", "All things that breathe air are dolphins", "Dolphins live on land", "Mammals are dolphins"],
    correct: 0,
    explanation: "Dolphins are mammals, and all mammals breathe air, so dolphins breathe air." },
  { id: "Y2LR17", category: "Logical Reasoning", difficulty: 2,
    question: "Alex scored more than Beth. Cara scored more than Beth. Alex scored more than Cara. Who scored the least?",
    visual: "text",
    options: ["Beth", "Cara", "Alex", "They all scored the same"], correct: 0,
    explanation: "Alex > Cara > Beth. Beth scored the least." },
  { id: "Y2LR18", category: "Logical Reasoning", difficulty: 2,
    question: "Today is Friday. What day was it 4 days ago?",
    visual: "text",
    options: ["Monday", "Tuesday", "Sunday", "Wednesday"], correct: 0,
    explanation: "Friday − 4 days: Thursday (1), Wednesday (2), Tuesday (3), Monday (4)." },
  { id: "Y2LR19", category: "Logical Reasoning", difficulty: 1,
    question: "No reptiles have fur. A lizard is a reptile. Therefore:",
    visual: "text",
    options: ["A lizard does not have fur", "All animals without fur are lizards", "Some reptiles have fur", "Lizards are not reptiles"],
    correct: 0,
    explanation: "No reptiles have fur. A lizard is a reptile. So a lizard does not have fur." },
  { id: "Y2LR20", category: "Logical Reasoning", difficulty: 1,
    question: "The red book is thicker than the blue book. The green book is thinner than the blue book. Which book is the thinnest?",
    visual: "text",
    options: ["The green book", "The blue book", "The red book", "They are all the same"], correct: 0,
    explanation: "Red > Blue > Green in thickness. The green book is the thinnest." },
  { id: "Y2LR21", category: "Logical Reasoning", difficulty: 2,
    question: "If you eat too much candy, you get a toothache. Sam does not have a toothache. What can you conclude?",
    visual: "text",
    options: ["Sam did not eat too much candy", "Sam ate too much candy", "Sam likes candy", "Sam has healthy teeth because of candy"],
    correct: 0,
    explanation: "If eating too much candy causes a toothache, and Sam has no toothache, then Sam did not eat too much candy." },
  { id: "Y2LR22", category: "Logical Reasoning", difficulty: 2,
    question: "All cats have tails. This animal has a tail. Is it definitely a cat?",
    visual: "text",
    options: ["Not necessarily — many animals have tails", "Yes, it must be a cat", "No animal other than a cat has a tail", "Cats do not have tails"],
    correct: 0,
    explanation: "All cats have tails, but dogs, monkeys, and many other animals also have tails." },
  { id: "Y2LR23", category: "Logical Reasoning", difficulty: 2,
    question: "Mia's bag is heavier than Nora's. Olivia's bag is heavier than Nora's. Mia's bag is heavier than Olivia's. Who has the lightest bag?",
    visual: "text",
    options: ["Nora", "Olivia", "Mia", "They all weigh the same"], correct: 0,
    explanation: "Mia > Olivia > Nora. Nora has the lightest bag." },
  { id: "Y2LR24", category: "Logical Reasoning", difficulty: 2,
    question: "If today is Tuesday, what day will it be in 10 days?",
    visual: "text",
    options: ["Friday", "Thursday", "Saturday", "Wednesday"], correct: 0,
    explanation: "10 days = 1 full week + 3 days. Tuesday + 3 days = Friday." },
  { id: "Y2LR25", category: "Logical Reasoning", difficulty: 1,
    question: "All birds have wings. All eagles are birds. Therefore:",
    visual: "text",
    options: ["All eagles have wings", "All things with wings are eagles", "Some eagles don't have wings", "Eagles are not birds"],
    correct: 0,
    explanation: "Eagles are birds, and all birds have wings, so all eagles have wings." },
  { id: "Y2LR26", category: "Logical Reasoning", difficulty: 2,
    question: "Every student in the class wears a uniform. Tom wears a uniform. Is Tom definitely a student in the class?",
    visual: "text",
    options: ["Not necessarily — other people might wear uniforms too", "Yes, Tom must be in the class", "No one outside the class wears a uniform", "Tom is a teacher"],
    correct: 0,
    explanation: "All students wear uniforms, but wearing a uniform doesn't prove you are a student in that class." },

  // =========================================================================
  // SPATIAL REASONING (26 questions: Y2SR1 – Y2SR26)
  // =========================================================================

  { id: "Y2SR1", category: "Spatial Reasoning", difficulty: 1,
    question: "How many faces does a cube have?",
    visual: "text",
    options: ["6", "4", "8", "12"], correct: 0,
    explanation: "A cube has 6 faces: top, bottom, front, back, left, and right." },
  { id: "Y2SR2", category: "Spatial Reasoning", difficulty: 1,
    question: "If you cut a square diagonally, what shapes do you get?",
    visual: "text",
    options: ["Two triangles", "Two rectangles", "Two squares", "A triangle and a square"], correct: 0,
    explanation: "Cutting a square corner-to-corner gives you two identical triangles." },
  { id: "Y2SR3", category: "Spatial Reasoning", difficulty: 1,
    question: "How many edges does a cube have?",
    visual: "text",
    options: ["12", "8", "6", "10"], correct: 0,
    explanation: "A cube has 12 edges: 4 on top, 4 on bottom, and 4 connecting them." },
  { id: "Y2SR4", category: "Spatial Reasoning", difficulty: 2,
    question: "How many vertices (corners) does a cube have?",
    visual: "text",
    options: ["8", "6", "12", "4"], correct: 0,
    explanation: "A cube has 8 vertices: 4 on the top face and 4 on the bottom face." },
  { id: "Y2SR5", category: "Spatial Reasoning", difficulty: 2,
    question: "If you stack two cubes on top of each other, how many faces are visible from the outside?",
    visual: "text",
    options: ["10", "12", "8", "9"], correct: 0,
    explanation: "Two cubes have 12 faces total. 2 faces are hidden where they touch. 12 − 2 = 10." },
  { id: "Y2SR6", category: "Spatial Reasoning", difficulty: 2,
    question: "How many edges does a triangular pyramid (tetrahedron) have?",
    visual: "text",
    options: ["6", "4", "8", "3"], correct: 0,
    explanation: "A tetrahedron has 6 edges: 3 on the base and 3 connecting to the apex." },
  { id: "Y2SR7", category: "Spatial Reasoning", difficulty: 2,
    question: "What shape do you get when you look at a sphere from any direction?",
    visual: "text",
    options: ["Circle", "Square", "Oval", "Semicircle"], correct: 0,
    explanation: "A sphere looks like a circle from every viewing angle." },
  { id: "Y2SR8", category: "Spatial Reasoning", difficulty: 2,
    question: "How many faces does a triangular prism have?",
    visual: "text",
    options: ["5", "4", "6", "3"], correct: 0,
    explanation: "A triangular prism has 2 triangular faces and 3 rectangular faces = 5." },

  { id: "Y2SR9", category: "Spatial Reasoning", difficulty: 1,
    question: "How many faces does a rectangular box (rectangular prism) have?",
    visual: "text",
    options: ["6", "4", "8", "10"], correct: 0,
    explanation: "A rectangular box has 6 faces: top, bottom, front, back, left, and right." },
  { id: "Y2SR10", category: "Spatial Reasoning", difficulty: 1,
    question: "How many edges does a rectangular box (rectangular prism) have?",
    visual: "text",
    options: ["12", "8", "6", "10"], correct: 0,
    explanation: "A rectangular box has 12 edges: 4 on top, 4 on bottom, and 4 connecting them." },
  { id: "Y2SR11", category: "Spatial Reasoning", difficulty: 1,
    question: "How many vertices (corners) does a rectangular box have?",
    visual: "text",
    options: ["8", "6", "10", "12"], correct: 0,
    explanation: "A rectangular box has 8 vertices: 4 on the top face and 4 on the bottom face." },
  { id: "Y2SR12", category: "Spatial Reasoning", difficulty: 1,
    question: "How many faces does a square-based pyramid have?",
    visual: "text",
    options: ["5", "4", "6", "3"], correct: 0,
    explanation: "A square-based pyramid has 1 square base + 4 triangular sides = 5 faces." },
  { id: "Y2SR13", category: "Spatial Reasoning", difficulty: 2,
    question: "How many edges does a square-based pyramid have?",
    visual: "text",
    options: ["8", "6", "5", "10"], correct: 0,
    explanation: "A square-based pyramid has 4 base edges + 4 edges going up to the apex = 8 edges." },
  { id: "Y2SR14", category: "Spatial Reasoning", difficulty: 2,
    question: "How many vertices (corners) does a square-based pyramid have?",
    visual: "text",
    options: ["5", "4", "6", "8"], correct: 0,
    explanation: "A square-based pyramid has 4 base corners + 1 apex = 5 vertices." },
  { id: "Y2SR15", category: "Spatial Reasoning", difficulty: 1,
    question: "If you cut a rectangle in half along its length, what two shapes do you get?",
    visual: "text",
    options: ["Two smaller rectangles", "Two triangles", "A square and a rectangle", "Two circles"], correct: 0,
    explanation: "Cutting a rectangle straight across its length gives two smaller rectangles." },
  { id: "Y2SR16", category: "Spatial Reasoning", difficulty: 1,
    question: "How many flat faces does a cylinder have?",
    visual: "text",
    options: ["2", "1", "3", "0"], correct: 0,
    explanation: "A cylinder has 2 flat circular faces: one on the top and one on the bottom." },
  { id: "Y2SR17", category: "Spatial Reasoning", difficulty: 2,
    question: "How many vertices (corners) does a triangular pyramid (tetrahedron) have?",
    visual: "text",
    options: ["4", "3", "5", "6"], correct: 0,
    explanation: "A tetrahedron has 4 vertices: 3 on the base triangle and 1 at the apex." },
  { id: "Y2SR18", category: "Spatial Reasoning", difficulty: 2,
    question: "A cross shape (+) made of 6 connected squares can be folded into which 3D shape?",
    visual: "text",
    options: ["A cube", "A pyramid", "A cylinder", "A prism"], correct: 0,
    explanation: "A cross-shaped net of 6 squares folds up into a cube." },
  { id: "Y2SR19", category: "Spatial Reasoning", difficulty: 2,
    question: "How many faces does a hexagonal prism have?",
    visual: "text",
    options: ["8", "6", "7", "10"], correct: 0,
    explanation: "A hexagonal prism has 2 hexagonal faces + 6 rectangular faces = 8 faces." },
  { id: "Y2SR20", category: "Spatial Reasoning", difficulty: 2,
    question: "How many edges does a triangular prism have?",
    visual: "text",
    options: ["9", "6", "8", "12"], correct: 0,
    explanation: "A triangular prism has 3 top edges + 3 bottom edges + 3 connecting edges = 9." },
  { id: "Y2SR21", category: "Spatial Reasoning", difficulty: 1,
    question: "How many flat faces does a cone have?",
    visual: "text",
    options: ["1", "2", "0", "3"], correct: 0,
    explanation: "A cone has just 1 flat face — the circular base." },
  { id: "Y2SR22", category: "Spatial Reasoning", difficulty: 2,
    question: "How many vertices (corners) does a triangular prism have?",
    visual: "text",
    options: ["6", "5", "8", "4"], correct: 0,
    explanation: "A triangular prism has 3 vertices on top + 3 on the bottom = 6 vertices." },
  { id: "Y2SR23", category: "Spatial Reasoning", difficulty: 1,
    question: "If you unfold a cube flat (make a net), how many squares will you see?",
    visual: "text",
    options: ["6", "4", "8", "5"], correct: 0,
    explanation: "A cube has 6 faces, so its net is made of 6 squares." },
  { id: "Y2SR24", category: "Spatial Reasoning", difficulty: 2,
    question: "How many faces does a pentagonal prism have?",
    visual: "text",
    options: ["7", "5", "10", "8"], correct: 0,
    explanation: "A pentagonal prism has 2 pentagonal faces + 5 rectangular faces = 7 faces." },
  { id: "Y2SR25", category: "Spatial Reasoning", difficulty: 2,
    question: "If 4 cubes are glued in a row face-to-face, how many faces are visible from the outside?",
    visual: "text",
    options: ["18", "20", "16", "24"], correct: 0,
    explanation: "4 cubes have 24 faces total. 3 joints × 2 hidden faces = 6 hidden. 24 − 6 = 18." },
  { id: "Y2SR26", category: "Spatial Reasoning", difficulty: 1,
    question: "A sphere has how many edges?",
    visual: "text",
    options: ["0", "1", "2", "Infinite"], correct: 0,
    explanation: "A sphere is perfectly round and has no edges at all." },

  // =========================================================================
  // MATHEMATICAL PUZZLES (26 questions: Y2MP1 – Y2MP26)
  // =========================================================================

  { id: "Y2MP1", category: "Mathematical Puzzles", difficulty: 1,
    question: "A farmer has 17 sheep. All but 9 run away. How many sheep are left?",
    visual: "text",
    options: ["9", "8", "17", "0"], correct: 0,
    explanation: "'All but 9 run away' means 9 stay. So 9 sheep are left." },
  { id: "Y2MP2", category: "Mathematical Puzzles", difficulty: 1,
    question: "You are in a race and overtake the person in 2nd place. What position are you now?",
    visual: "text",
    options: ["2nd", "1st", "3rd", "4th"], correct: 0,
    explanation: "If you overtake the person in 2nd, you take their spot — you're now 2nd, not 1st." },
  { id: "Y2MP3", category: "Mathematical Puzzles", difficulty: 1,
    question: "How many months have 28 days?",
    visual: "text",
    options: ["All 12", "1", "2", "None"], correct: 0,
    explanation: "All 12 months have at least 28 days." },
  { id: "Y2MP4", category: "Mathematical Puzzles", difficulty: 2,
    question: "If you have 3 apples and take away 2, how many do you have?",
    visual: "text",
    options: ["2", "1", "3", "0"], correct: 0,
    explanation: "You took away 2 apples, so you now have those 2 apples." },
  { id: "Y2MP5", category: "Mathematical Puzzles", difficulty: 2,
    question: "A doctor gives you 3 pills and tells you to take one every 30 minutes. How long do the pills last?",
    visual: "text",
    options: ["60 minutes", "90 minutes", "30 minutes", "120 minutes"], correct: 0,
    explanation: "Take the 1st pill at 0 min, 2nd at 30 min, 3rd at 60 min. Total: 60 minutes." },
  { id: "Y2MP6", category: "Mathematical Puzzles", difficulty: 2,
    question: "If there are 6 apples and you take away 4, how many do you have?",
    visual: "text",
    options: ["4", "2", "6", "0"], correct: 0,
    explanation: "You took 4 apples, so you have 4." },
  { id: "Y2MP7", category: "Mathematical Puzzles", difficulty: 2,
    question: "Find the missing number where every row sums to 15.",
    visual: "number-grid", grid: [[8, 1, 6], [3, 5, 7], [4, "?", 2]],
    options: ["9", "8", "7", "6"], correct: 0,
    explanation: "Bottom row: 4 + ? + 2 = 15, so ? = 9." },
  { id: "Y2MP8", category: "Mathematical Puzzles", difficulty: 2,
    question: "How many legs do 5 dogs and 3 birds have in total?",
    visual: "text",
    options: ["26", "32", "20", "24"], correct: 0,
    explanation: "Dogs: 5 × 4 = 20 legs. Birds: 3 × 2 = 6 legs. Total: 26." },

  { id: "Y2MP9", category: "Mathematical Puzzles", difficulty: 1,
    question: "What weighs more: a kilogram of feathers or a kilogram of iron?",
    visual: "text",
    options: ["They weigh the same", "Iron", "Feathers", "Cannot tell"], correct: 0,
    explanation: "A kilogram is a kilogram, regardless of the material. They weigh the same." },
  { id: "Y2MP10", category: "Mathematical Puzzles", difficulty: 1,
    question: "A baker has 36 cookies and packs them equally into 4 boxes. How many cookies are in each box?",
    visual: "text",
    options: ["9", "8", "6", "12"], correct: 0,
    explanation: "36 ÷ 4 = 9 cookies per box." },
  { id: "Y2MP11", category: "Mathematical Puzzles", difficulty: 1,
    question: "Three friends share 24 marbles equally. How many does each friend get?",
    visual: "text",
    options: ["8", "6", "12", "7"], correct: 0,
    explanation: "24 ÷ 3 = 8 marbles each." },
  { id: "Y2MP12", category: "Mathematical Puzzles", difficulty: 1,
    question: "A car travels 60 kilometres in 1 hour. How far does it travel in 3 hours at the same speed?",
    visual: "text",
    options: ["180 km", "120 km", "200 km", "160 km"], correct: 0,
    explanation: "60 × 3 = 180 km." },
  { id: "Y2MP13", category: "Mathematical Puzzles", difficulty: 2,
    question: "If 5 machines take 5 minutes to make 5 toys, how long would 10 machines take to make 10 toys?",
    visual: "text",
    options: ["5 minutes", "10 minutes", "1 minute", "50 minutes"], correct: 0,
    explanation: "Each machine makes 1 toy in 5 minutes. 10 machines each making 1 toy still takes 5 minutes." },
  { id: "Y2MP14", category: "Mathematical Puzzles", difficulty: 2,
    question: "In this grid, every row adds up to 15. What is the missing number?",
    visual: "number-grid", grid: [[2, 7, 6], [9, 5, 1], [4, "?", 8]],
    options: ["3", "4", "5", "2"], correct: 0,
    explanation: "Bottom row: 4 + ? + 8 = 15, so ? = 3." },
  { id: "Y2MP15", category: "Mathematical Puzzles", difficulty: 1,
    question: "A classroom has 5 rows of desks with 6 desks in each row. How many desks are there in total?",
    visual: "text",
    options: ["30", "25", "35", "11"], correct: 0,
    explanation: "5 × 6 = 30 desks." },
  { id: "Y2MP16", category: "Mathematical Puzzles", difficulty: 1,
    question: "48 candies are shared equally among 8 children. How many does each child get?",
    visual: "text",
    options: ["6", "8", "5", "7"], correct: 0,
    explanation: "48 ÷ 8 = 6 candies each." },
  { id: "Y2MP17", category: "Mathematical Puzzles", difficulty: 2,
    question: "If 3 painters can paint 3 walls in 3 hours, how many walls can 6 painters paint in 6 hours?",
    visual: "text",
    options: ["12", "6", "18", "9"], correct: 0,
    explanation: "Each painter paints 1 wall in 3 hours. In 6 hours each painter paints 2 walls. 6 × 2 = 12." },
  { id: "Y2MP18", category: "Mathematical Puzzles", difficulty: 2,
    question: "How many times can you subtract 5 from 25?",
    visual: "text",
    options: ["Once — after that it is no longer 25", "5 times", "25 times", "Infinite times"], correct: 0,
    explanation: "You can only subtract 5 from 25 once. After that you are subtracting from 20, not 25." },
  { id: "Y2MP19", category: "Mathematical Puzzles", difficulty: 1,
    question: "A book has 120 pages. Tom reads 15 pages each day. How many days will it take him to finish?",
    visual: "text",
    options: ["8 days", "10 days", "6 days", "12 days"], correct: 0,
    explanation: "120 ÷ 15 = 8 days." },
  { id: "Y2MP20", category: "Mathematical Puzzles", difficulty: 2,
    question: "In this grid, every row adds up to 15. What is the missing number?",
    visual: "number-grid", grid: [[6, 1, 8], [7, 5, 3], [2, "?", 4]],
    options: ["9", "8", "7", "6"], correct: 0,
    explanation: "Bottom row: 2 + ? + 4 = 15, so ? = 9." },
  { id: "Y2MP21", category: "Mathematical Puzzles", difficulty: 1,
    question: "A spider has 8 legs and a bee has 6 legs. How many legs do 4 spiders and 3 bees have altogether?",
    visual: "text",
    options: ["50", "48", "56", "42"], correct: 0,
    explanation: "Spiders: 4 × 8 = 32 legs. Bees: 3 × 6 = 18 legs. Total: 32 + 18 = 50." },
  { id: "Y2MP22", category: "Mathematical Puzzles", difficulty: 2,
    question: "A girl has as many brothers as she has sisters. Her brother has twice as many sisters as he has brothers. How many children are in the family?",
    visual: "text",
    options: ["7", "5", "6", "4"], correct: 0,
    explanation: "Let boys = b, girls = g. Girl sees: b brothers, g−1 sisters, so b = g−1. Boy sees: g sisters, b−1 brothers, so g = 2(b−1). Solving: b = 3, g = 4. Total = 7." },
  { id: "Y2MP23", category: "Mathematical Puzzles", difficulty: 1,
    question: "A train has 8 carriages. Each carriage has 30 seats. How many seats does the train have in total?",
    visual: "text",
    options: ["240", "230", "200", "280"], correct: 0,
    explanation: "8 × 30 = 240 seats." },
  { id: "Y2MP24", category: "Mathematical Puzzles", difficulty: 2,
    question: "In a farmyard there are chickens and rabbits. Together they have 10 heads and 28 legs. How many rabbits are there?",
    visual: "text",
    options: ["4", "6", "5", "3"], correct: 0,
    explanation: "10 heads means 10 animals. If all were chickens: 20 legs. Extra legs: 28 − 20 = 8. Each rabbit adds 2 extra legs. 8 ÷ 2 = 4 rabbits." },
  { id: "Y2MP25", category: "Mathematical Puzzles", difficulty: 1,
    question: "A pizza is cut into 8 equal slices. Three friends each eat 2 slices. How many slices are left?",
    visual: "text",
    options: ["2", "3", "1", "4"], correct: 0,
    explanation: "3 friends × 2 slices = 6 eaten. 8 − 6 = 2 slices left." },
  { id: "Y2MP26", category: "Mathematical Puzzles", difficulty: 2,
    question: "Every row and every column in this grid adds up to the same number. What is the missing number?",
    visual: "number-grid", grid: [[5, 10, 3], [4, 6, 8], [9, 2, "?"]],
    options: ["7", "8", "6", "5"], correct: 0,
    explanation: "Row 1: 5 + 10 + 3 = 18. Row 3: 9 + 2 + ? = 18, so ? = 7. Check columns: 3 + 8 + 7 = 18 ✓." }
];
