// ============================================================================
// AGE 12–15: Approaching adult complexity, normed for this age group.
//            Abstract reasoning, complex number grids, advanced math,
//            spatial rotation, cube-cutting/painting, cross-sections.
//            130 questions (26 per category), test uses random selection.
// ============================================================================
const QUESTIONS_AGE_12_15 = [

  // =========================================================================
  // PATTERN RECOGNITION  (26 questions — Y3PR1 … Y3PR26)
  // =========================================================================

  // --- Existing 8 (Y3PR1–Y3PR8) ---
  { id: "Y3PR1", category: "Pattern Recognition", difficulty: 1,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 4, 9], [16, 25, 36], [49, 64, "?"]],
    options: ["81", "72", "100", "90"], correct: 0,
    explanation: "These are perfect squares: 1², 2², 3², ... 8², 9² = 81." },
  { id: "Y3PR2", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next?",
    visual: "sequence", sequence: ["◇", "◇◆", "◇◆◇", "◇◆◇◆", "?"],
    options: ["◇◆◇◆◇", "◆◇◆◇◆", "◇◇◇◇◇", "◆◆◆◆◆"], correct: 0,
    explanation: "The sequence alternates ◇ and ◆, adding one each time. Next: ◇◆◇◆◇." },
  { id: "Y3PR3", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 4, 8], [3, 6, 12], [5, 10, "?"]],
    options: ["20", "15", "25", "30"], correct: 0,
    explanation: "Each row: col2 = col1 × 2, col3 = col1 × 4. So 5 × 4 = 20." },
  { id: "Y3PR4", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 4, 8], [3, 9, 27], [4, 16, "?"]],
    options: ["64", "48", "32", "56"], correct: 0,
    explanation: "Row 1: 2^1, 2^2, 2^3. Row 2: 3^1, 3^2, 3^3. Row 3: 4^1, 4^2, 4^3 = 64." },
  { id: "Y3PR5", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 3, 5], [2, 6, 10], [3, 9, "?"]],
    options: ["15", "12", "18", "21"], correct: 0,
    explanation: "Column 2 = col1 × 3. Column 3 = col1 × 5. So 3 × 5 = 15." },
  { id: "Y3PR6", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 1, 1], [2, 4, 8], [3, 9, "?"]],
    options: ["27", "18", "12", "36"], correct: 0,
    explanation: "Row pattern: n^1, n^2, n^3. Row 3: 3^1=3, 3^2=9, 3^3=27." },
  { id: "Y3PR7", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[10, 8, 6], [9, 6, 3], [8, 4, "?"]],
    options: ["0", "2", "1", "-2"], correct: 0,
    explanation: "Row 1: decreases by 2. Row 2: decreases by 3. Row 3: decreases by 4. So 8, 4, 0." },
  { id: "Y3PR8", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 3, 5], [7, 11, 13], [17, 19, "?"]],
    options: ["23", "21", "25", "29"], correct: 0,
    explanation: "These are consecutive prime numbers: 2, 3, 5, 7, 11, 13, 17, 19, 23." },

  // --- New 18 (Y3PR9–Y3PR26) ---
  { id: "Y3PR9", category: "Pattern Recognition", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 4, 8, 16, 32, 64, "?"],
    options: ["128", "100", "96", "256"], correct: 0,
    explanation: "Each number doubles: ×2 each time. 64 × 2 = 128." },
  { id: "Y3PR10", category: "Pattern Recognition", difficulty: 1,
    question: "What comes next?",
    visual: "sequence", sequence: ["△", "△□", "△□△", "△□△□", "?"],
    options: ["△□△□△", "□△□△□", "△△△△△", "□□□□□"], correct: 0,
    explanation: "The pattern alternates △ and □, adding one symbol each step. Next: △□△□△." },
  { id: "Y3PR11", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 1, 2], [2, 3, 5], [5, 8, "?"]],
    options: ["13", "11", "14", "10"], correct: 0,
    explanation: "Each row follows col3 = col1 + col2 (Fibonacci-like). Row 3: 5 + 8 = 13." },
  { id: "Y3PR12", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 3, 6], [4, 5, 20], [6, 7, "?"]],
    options: ["42", "36", "48", "13"], correct: 0,
    explanation: "Rule: col1 × col2 = col3. So 6 × 7 = 42." },
  { id: "Y3PR13", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[5, 8, 2], [6, 3, 6], [4, 7, "?"]],
    options: ["4", "5", "6", "3"], correct: 0,
    explanation: "Each row sums to 15. Row 3: 4 + 7 + ? = 15, so ? = 4." },
  { id: "Y3PR14", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 2, 6], [2, 6, 24], [6, 24, "?"]],
    options: ["120", "100", "72", "48"], correct: 0,
    explanation: "Factorials flow through the grid: 1!, 2!, 3!, 4!, 5!. Row 3: 3!=6, 4!=24, 5!=120." },
  { id: "Y3PR15", category: "Pattern Recognition", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 1, 3, 4, 7, 11, "?"],
    options: ["18", "15", "22", "16"], correct: 0,
    explanation: "Each term is the sum of the two before it: 7 + 11 = 18." },
  { id: "Y3PR16", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 5, 9], [2, 10, 18], [3, 15, "?"]],
    options: ["27", "24", "30", "21"], correct: 0,
    explanation: "Col2 = col1 × 5. Col3 = col1 × 9. Row 3: 3 × 9 = 27." },
  { id: "Y3PR17", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[3, 5, 7], [5, 7, 9], [7, 9, "?"]],
    options: ["11", "13", "10", "12"], correct: 0,
    explanation: "Each row and column increases by 2. Row 3: 7, 9, 11." },
  { id: "Y3PR18", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 8, 9], [2, 7, 9], [3, 6, "?"]],
    options: ["9", "8", "10", "7"], correct: 0,
    explanation: "In each row, col1 + col2 = 9. So col3 is always 9." },
  { id: "Y3PR19", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 1, 2], [8, 4, 12], [27, 9, "?"]],
    options: ["36", "30", "27", "45"], correct: 0,
    explanation: "Col1 = n³, col2 = n². Col3 = n³ + n². Row 3: 27 + 9 = 36." },
  { id: "Y3PR20", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 4, 16], [3, 9, 81], [5, 25, "?"]],
    options: ["625", "125", "250", "500"], correct: 0,
    explanation: "Col2 = col1². Col3 = col2² (= col1⁴). Row 3: 25² = 625." },
  { id: "Y3PR21", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 3, 6], [10, 15, 21], [28, 36, "?"]],
    options: ["45", "40", "42", "50"], correct: 0,
    explanation: "Consecutive triangular numbers T(n) = n(n+1)/2. T(9) = 9×10/2 = 45." },
  { id: "Y3PR22", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[1, 4, 27], [2, 9, 64], [3, 16, "?"]],
    options: ["125", "100", "81", "150"], correct: 0,
    explanation: "Col1 = n, col2 = (n+1)², col3 = (n+2)³. Row 3: 5³ = 125." },
  { id: "Y3PR23", category: "Pattern Recognition", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 3, 7, 15, 31, "?"],
    options: ["63", "47", "62", "64"], correct: 0,
    explanation: "Each term = previous × 2 + 1. So 31 × 2 + 1 = 63." },
  { id: "Y3PR24", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 8, 16], [3, 27, 81], [4, 64, "?"]],
    options: ["256", "128", "192", "320"], correct: 0,
    explanation: "Col1 = n, col2 = n³, col3 = n⁴. Row 3: 4⁴ = 256." },
  { id: "Y3PR25", category: "Pattern Recognition", difficulty: 2,
    question: "What number is missing?",
    visual: "number-grid", grid: [[3, 5, 8], [7, 11, 18], [13, 17, "?"]],
    options: ["30", "23", "29", "31"], correct: 0,
    explanation: "Col3 = col1 + col2. Row 3: 13 + 17 = 30." },
  { id: "Y3PR26", category: "Pattern Recognition", difficulty: 3,
    question: "What number is missing?",
    visual: "number-grid", grid: [[2, 3, 13], [4, 1, 17], [5, 7, "?"]],
    options: ["74", "60", "35", "84"], correct: 0,
    explanation: "Rule: col1² + col2² = col3. Row 3: 25 + 49 = 74." },

  // =========================================================================
  // NUMERICAL REASONING  (26 questions — Y3NR1 … Y3NR26)
  // =========================================================================

  // --- Existing 8 (Y3NR1–Y3NR8) ---
  { id: "Y3NR1", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 1, 2, 3, 5, 8, "?"],
    options: ["13", "11", "10", "12"], correct: 0,
    explanation: "Each number is the sum of the two before it (Fibonacci). 5 + 8 = 13." },
  { id: "Y3NR2", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 4, 9, 16, 25, "?"],
    options: ["36", "30", "49", "35"], correct: 0,
    explanation: "These are perfect squares: 1², 2², 3², 4², 5², 6² = 36." },
  { id: "Y3NR3", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 6, 12, 20, 30, "?"],
    options: ["42", "40", "36", "44"], correct: 0,
    explanation: "Differences increase by 2: +4, +6, +8, +10, +12. So 30 + 12 = 42." },
  { id: "Y3NR4", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 3, 5, 7, 11, 13, "?"],
    options: ["17", "15", "16", "19"], correct: 0,
    explanation: "These are consecutive prime numbers. The next prime after 13 is 17." },
  { id: "Y3NR5", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 8, 27, 64, 125, "?"],
    options: ["216", "196", "256", "200"], correct: 0,
    explanation: "These are perfect cubes: 1³, 2³, 3³, 4³, 5³, 6³ = 216." },
  { id: "Y3NR6", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 3, 6, 10, 15, 21, "?"],
    options: ["28", "27", "26", "30"], correct: 0,
    explanation: "Triangular numbers: +2, +3, +4, +5, +6, +7. So 21 + 7 = 28." },
  { id: "Y3NR7", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [3, 6, 11, 18, 27, "?"],
    options: ["38", "36", "35", "40"], correct: 0,
    explanation: "Differences increase by 2 each time: +3, +5, +7, +9, +11. So 27 + 11 = 38." },
  { id: "Y3NR8", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 5, 11, 23, 47, "?"],
    options: ["95", "94", "96", "93"], correct: 0,
    explanation: "Each number is (previous × 2) + 1. So 47 × 2 + 1 = 95." },

  // --- New 18 (Y3NR9–Y3NR26) ---
  { id: "Y3NR9", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 6, 18, 54, 162, "?"],
    options: ["486", "324", "500", "480"], correct: 0,
    explanation: "Each number is multiplied by 3. 162 × 3 = 486." },
  { id: "Y3NR10", category: "Numerical Reasoning", difficulty: 1,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [100, 81, 64, 49, 36, "?"],
    options: ["25", "16", "30", "20"], correct: 0,
    explanation: "Descending perfect squares: 10², 9², 8², 7², 6², 5² = 25." },
  { id: "Y3NR11", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 5, 10, 13, 26, "?"],
    options: ["29", "52", "30", "28"], correct: 0,
    explanation: "Alternating operations: ×2, +3, ×2, +3, ×2, +3. So 26 + 3 = 29." },
  { id: "Y3NR12", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 6, 24, 120, "?"],
    options: ["720", "600", "240", "840"], correct: 0,
    explanation: "These are factorials: 1!, 2!, 3!, 4!, 5!, 6! = 720." },
  { id: "Y3NR13", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [4, 7, 13, 25, 49, "?"],
    options: ["97", "73", "96", "98"], correct: 0,
    explanation: "Each term = previous × 2 − 1. So 49 × 2 − 1 = 97." },
  { id: "Y3NR14", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 5, 10, 17, 26, "?"],
    options: ["37", "35", "38", "36"], correct: 0,
    explanation: "Differences are consecutive odd numbers: +1, +3, +5, +7, +9, +11. So 26 + 11 = 37." },
  { id: "Y3NR15", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [0, 3, 8, 15, 24, "?"],
    options: ["35", "30", "33", "40"], correct: 0,
    explanation: "Pattern: n² − 1 for n = 1, 2, 3, 4, 5, 6. So 6² − 1 = 35." },
  { id: "Y3NR16", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [3, 8, 16, 21, 42, "?"],
    options: ["47", "84", "48", "52"], correct: 0,
    explanation: "Alternating operations: +5, ×2, +5, ×2, +5. So 42 + 5 = 47." },
  { id: "Y3NR17", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [0, 1, 1, 2, 3, 5, 8, 13, "?"],
    options: ["21", "18", "20", "26"], correct: 0,
    explanation: "Fibonacci sequence starting from 0. Each = sum of previous two. 8 + 13 = 21." },
  { id: "Y3NR18", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 3, 2, 6, 5, 15, "?"],
    options: ["14", "45", "13", "12"], correct: 0,
    explanation: "Alternating operations: ×3, −1, ×3, −1, ×3, −1. So 15 − 1 = 14." },
  { id: "Y3NR19", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 4, 7, 11, 16, "?"],
    options: ["22", "21", "23", "20"], correct: 0,
    explanation: "Differences increase by 1: +1, +2, +3, +4, +5, +6. So 16 + 6 = 22." },
  { id: "Y3NR20", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [3, 5, 9, 15, 23, "?"],
    options: ["33", "31", "35", "29"], correct: 0,
    explanation: "Differences increase by 2: +2, +4, +6, +8, +10. So 23 + 10 = 33." },
  { id: "Y3NR21", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 4, 13, 40, 121, "?"],
    options: ["364", "363", "243", "400"], correct: 0,
    explanation: "Each term = previous × 3 + 1. So 121 × 3 + 1 = 364." },
  { id: "Y3NR22", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 6, 12, 20, 30, 42, "?"],
    options: ["56", "52", "60", "48"], correct: 0,
    explanation: "Pattern: n(n+1) for n = 1,2,3,… Differences: +4, +6, +8, +10, +12, +14. So 42 + 14 = 56." },
  { id: "Y3NR23", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 5, 14, 30, 55, "?"],
    options: ["91", "85", "80", "100"], correct: 0,
    explanation: "Sum of squares: 1², 1²+2², …, 1²+…+5² = 55. Next: 55 + 6² = 91." },
  { id: "Y3NR24", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [1, 2, 3, 5, 8, 13, 21, "?"],
    options: ["34", "29", "42", "32"], correct: 0,
    explanation: "Fibonacci-like: each = sum of previous two. 13 + 21 = 34." },
  { id: "Y3NR25", category: "Numerical Reasoning", difficulty: 2,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 9, 28, 65, 126, "?"],
    options: ["217", "210", "220", "215"], correct: 0,
    explanation: "Pattern: n³ + 1. For n = 1,2,3,4,5,6: 6³ + 1 = 217." },
  { id: "Y3NR26", category: "Numerical Reasoning", difficulty: 3,
    question: "What number comes next?",
    visual: "num-sequence", sequence: [2, 10, 30, 68, 130, "?"],
    options: ["222", "210", "216", "250"], correct: 0,
    explanation: "Pattern: n³ + n. For n = 1,2,3,4,5,6: 6³ + 6 = 222." },

  // =========================================================================
  // LOGICAL REASONING  (26 questions — Y3LR1 … Y3LR26)
  // =========================================================================

  // --- Existing 8 (Y3LR1–Y3LR8) ---
  { id: "Y3LR1", category: "Logical Reasoning", difficulty: 1,
    question: "In a row of students, Emma is 4th from the left and 5th from the right. How many students are in the row?",
    visual: "text",
    options: ["8", "9", "7", "10"], correct: 0,
    explanation: "Position from left + position from right − 1 = total. 4 + 5 − 1 = 8." },
  { id: "Y3LR2", category: "Logical Reasoning", difficulty: 1,
    question: "In a class of 20, 12 like soccer and 10 like basketball. If everyone likes at least one sport, how many like both?",
    visual: "text",
    options: ["2", "10", "8", "0"], correct: 0,
    explanation: "By inclusion-exclusion: 12 + 10 − 20 = 2. So 2 students like both." },
  { id: "Y3LR3", category: "Logical Reasoning", difficulty: 2,
    question: "If the day after tomorrow is Wednesday, what day is today?",
    visual: "text",
    options: ["Monday", "Tuesday", "Sunday", "Wednesday"], correct: 0,
    explanation: "If the day after tomorrow is Wednesday, then tomorrow is Tuesday, and today is Monday." },
  { id: "Y3LR4", category: "Logical Reasoning", difficulty: 2,
    question: "P is heavier than Q. R is lighter than S. S is lighter than Q. Who is the lightest?",
    visual: "text",
    options: ["R", "S", "Q", "P"], correct: 0,
    explanation: "P > Q > S > R. R is the lightest." },
  { id: "Y3LR5", category: "Logical Reasoning", difficulty: 2,
    question: "In a row of people, Tom is 5th from the left and 6th from the right. How many people are in the row?",
    visual: "text",
    options: ["10", "11", "9", "12"], correct: 0,
    explanation: "Position from left + position from right − 1 = total. 5 + 6 − 1 = 10." },
  { id: "Y3LR6", category: "Logical Reasoning", difficulty: 3,
    question: "In a class of 30, 18 play football and 15 play basketball. If everyone plays at least one sport, how many play both?",
    visual: "text",
    options: ["3", "5", "12", "0"], correct: 0,
    explanation: "By inclusion-exclusion: 18 + 15 − 30 = 3. So 3 students play both." },
  { id: "Y3LR7", category: "Logical Reasoning", difficulty: 3,
    question: "If the day after tomorrow is two days before Thursday, what day is it today?",
    visual: "text",
    options: ["Sunday", "Monday", "Tuesday", "Saturday"], correct: 0,
    explanation: "Two days before Thursday is Tuesday. If the day after tomorrow is Tuesday, then today is Sunday." },
  { id: "Y3LR8", category: "Logical Reasoning", difficulty: 3,
    question: "X is older than Y. Z is younger than W. W is younger than Y. Who is the oldest?",
    visual: "text",
    options: ["X", "Y", "W", "Z"], correct: 0,
    explanation: "X > Y > W > Z. X is the oldest." },

  // --- New 18 (Y3LR9–Y3LR26) ---
  { id: "Y3LR9", category: "Logical Reasoning", difficulty: 1,
    question: "In a class of 25, 15 students have a cat and 13 have a dog. If every student has at least one pet, how many have both?",
    visual: "text",
    options: ["3", "2", "5", "8"], correct: 0,
    explanation: "By inclusion-exclusion: 15 + 13 − 25 = 3." },
  { id: "Y3LR10", category: "Logical Reasoning", difficulty: 1,
    question: "If today is Saturday, what day will it be 10 days from now?",
    visual: "text",
    options: ["Tuesday", "Monday", "Wednesday", "Sunday"], correct: 0,
    explanation: "10 days = 1 week + 3 days. Saturday + 3 days = Tuesday." },
  { id: "Y3LR11", category: "Logical Reasoning", difficulty: 2,
    question: "A is taller than B. C is shorter than A but taller than D. B is taller than C. Rank them tallest to shortest.",
    visual: "text",
    options: ["A, B, C, D", "A, C, B, D", "B, A, C, D", "A, B, D, C"], correct: 0,
    explanation: "A > B, A > C > D, B > C. So A > B > C > D." },
  { id: "Y3LR12", category: "Logical Reasoning", difficulty: 2,
    question: "In a line, Raj is 7th from the front and 13th from the back. How many people are in the line?",
    visual: "text",
    options: ["19", "20", "18", "21"], correct: 0,
    explanation: "Front position + back position − 1 = total. 7 + 13 − 1 = 19." },
  { id: "Y3LR13", category: "Logical Reasoning", difficulty: 2,
    question: "All Blips are Clops. No Clops are Drips. What can you conclude?",
    visual: "text",
    options: ["No Blips are Drips", "Some Blips are Drips", "All Drips are Blips", "Some Clops are Drips"], correct: 0,
    explanation: "All Blips are Clops, and no Clops are Drips, so no Blips can be Drips." },
  { id: "Y3LR14", category: "Logical Reasoning", difficulty: 2,
    question: "Today is Friday. What day was it 23 days ago?",
    visual: "text",
    options: ["Wednesday", "Thursday", "Tuesday", "Saturday"], correct: 0,
    explanation: "23 = 3 weeks + 2 days. Friday − 2 days = Wednesday." },
  { id: "Y3LR15", category: "Logical Reasoning", difficulty: 2,
    question: "Five friends — Amy, Ben, Cara, Dan, Eve — sit in a row. Cara is at the far left. Dan sits directly between Amy and Eve (adjacent to both). Eve is to the right of Dan. Amy is to the left of Ben. Who sits at the far right?",
    visual: "text",
    options: ["Ben", "Eve", "Dan", "Amy"], correct: 0,
    explanation: "Amy-Dan-Eve must be consecutive. With Cara at far left, the order is: Cara, Amy, Dan, Eve, Ben." },
  { id: "Y3LR16", category: "Logical Reasoning", difficulty: 2,
    question: "If 'whenever it rains the game is cancelled' is true, and the game was NOT cancelled, what can you conclude?",
    visual: "text",
    options: ["It did not rain", "It rained", "The game was played indoors", "Nothing can be concluded"], correct: 0,
    explanation: "Contrapositive: if rain → cancel, then not cancel → not rain." },
  { id: "Y3LR17", category: "Logical Reasoning", difficulty: 3,
    question: "In a class of 40, 25 like math, 22 like science, and 12 like both. How many like neither?",
    visual: "text",
    options: ["5", "3", "7", "10"], correct: 0,
    explanation: "At least one: 25 + 22 − 12 = 35. Neither: 40 − 35 = 5." },
  { id: "Y3LR18", category: "Logical Reasoning", difficulty: 3,
    question: "January 1st of a certain non-leap year is a Monday. What day of the week is March 1st?",
    visual: "text",
    options: ["Thursday", "Wednesday", "Friday", "Tuesday"], correct: 0,
    explanation: "Jan has 31 days, Feb has 28 days: 31 + 28 = 59 days later. 59 mod 7 = 3. Monday + 3 = Thursday." },
  { id: "Y3LR19", category: "Logical Reasoning", difficulty: 3,
    question: "Ana is older than both Bo and Cal. Cal is younger than Bo. Dana is older than Ana. List them youngest to oldest.",
    visual: "text",
    options: ["Cal, Bo, Ana, Dana", "Bo, Cal, Ana, Dana", "Cal, Ana, Bo, Dana", "Bo, Cal, Dana, Ana"], correct: 0,
    explanation: "Dana > Ana > Bo > Cal. Youngest to oldest: Cal, Bo, Ana, Dana." },
  { id: "Y3LR20", category: "Logical Reasoning", difficulty: 3,
    question: "Today is Wednesday. A meeting is scheduled for 100 days from now. What day of the week will it be?",
    visual: "text",
    options: ["Friday", "Thursday", "Saturday", "Wednesday"], correct: 0,
    explanation: "100 ÷ 7 = 14 remainder 2. Wednesday + 2 days = Friday." },
  { id: "Y3LR21", category: "Logical Reasoning", difficulty: 2,
    question: "The statement 'All swans are white' is given. Which would DISPROVE this?",
    visual: "text",
    options: ["Finding one black swan", "Finding many white swans", "Finding a white goose", "Not finding any swans"], correct: 0,
    explanation: "A single counterexample (one non-white swan) disproves a universal statement." },
  { id: "Y3LR22", category: "Logical Reasoning", difficulty: 3,
    question: "60 people: 35 speak English, 30 French, 20 Spanish. 15 speak English & French, 10 English & Spanish, 8 French & Spanish, 5 speak all three. How many speak at least one language?",
    visual: "text",
    options: ["57", "60", "55", "50"], correct: 0,
    explanation: "Inclusion-exclusion: 35 + 30 + 20 − 15 − 10 − 8 + 5 = 57." },
  { id: "Y3LR23", category: "Logical Reasoning", difficulty: 2,
    question: "If 'no reptiles have fur' is true, which must also be true?",
    visual: "text",
    options: ["All animals with fur are non-reptiles", "All reptiles are cold-blooded", "Some reptiles have scales", "No furry animals exist"], correct: 0,
    explanation: "Contrapositive: 'no reptiles have fur' is equivalent to 'if it has fur, it is not a reptile.'" },
  { id: "Y3LR24", category: "Logical Reasoning", difficulty: 3,
    question: "Sam has some apples. 'I have more than 5' is false. 'I have more than 2' is true. 'I have an even number' is true. How many apples does Sam have?",
    visual: "text",
    options: ["4", "2", "6", "3"], correct: 0,
    explanation: "At most 5, more than 2, and even. Possible: 4. (3 is odd, 6 > 5, 2 is not > 2.)" },
  { id: "Y3LR25", category: "Logical Reasoning", difficulty: 2,
    question: "In a row of 20 people, Alex is 6th from the left. What position is Alex from the right?",
    visual: "text",
    options: ["15th", "14th", "16th", "13th"], correct: 0,
    explanation: "Position from right = total − position from left + 1 = 20 − 6 + 1 = 15th." },
  { id: "Y3LR26", category: "Logical Reasoning", difficulty: 3,
    question: "If P → Q (when P is true, Q must be true) and Q → R, which must be true?",
    visual: "text",
    options: ["If P then R", "If R then P", "If Q then P", "P and R are the same"], correct: 0,
    explanation: "By the transitive property of implication: P → Q → R, so P → R." },

  // =========================================================================
  // SPATIAL REASONING  (26 questions — Y3SR1 … Y3SR26)
  // =========================================================================

  // --- Existing 8 (Y3SR1–Y3SR8) ---
  { id: "Y3SR1", category: "Spatial Reasoning", difficulty: 1,
    question: "If two cubes are glued face-to-face, how many faces are visible?",
    visual: "text",
    options: ["10", "12", "8", "11"], correct: 0,
    explanation: "Each cube has 6 faces. Gluing removes 1 face from each. 12 − 2 = 10." },
  { id: "Y3SR2", category: "Spatial Reasoning", difficulty: 1,
    question: "A cube is painted on all faces and cut into 8 smaller cubes (2×2×2). How many small cubes have exactly 3 painted faces?",
    visual: "text",
    options: ["8", "4", "6", "2"], correct: 0,
    explanation: "In a 2×2×2 cut, every small cube is a corner cube. All 8 have exactly 3 painted faces." },
  { id: "Y3SR3", category: "Spatial Reasoning", difficulty: 2,
    question: "A cube is painted red on all faces, then cut into 27 equal smaller cubes. How many small cubes have exactly one red face?",
    visual: "text",
    options: ["6", "8", "12", "1"], correct: 0,
    explanation: "The center of each face gives a small cube with exactly 1 painted face. There are 6 faces, so 6 cubes." },
  { id: "Y3SR4", category: "Spatial Reasoning", difficulty: 2,
    question: "How many faces does a regular tetrahedron have?",
    visual: "text",
    options: ["4", "3", "5", "6"], correct: 0,
    explanation: "A tetrahedron is a solid with 4 triangular faces." },
  { id: "Y3SR5", category: "Spatial Reasoning", difficulty: 2,
    question: "If three cubes are glued in a straight line, face-to-face, how many exposed faces does the combined shape have?",
    visual: "text",
    options: ["14", "18", "12", "16"], correct: 0,
    explanation: "3 cubes have 18 faces. 2 joints × 2 hidden faces = 4 hidden. 18 − 4 = 14." },
  { id: "Y3SR6", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is painted red on all faces, then cut into 27 equal smaller cubes. How many small cubes have NO red face at all?",
    visual: "text",
    options: ["1", "0", "6", "8"], correct: 0,
    explanation: "Only the very center cube of the 3×3×3 arrangement has no painted face. That's 1 cube." },
  { id: "Y3SR7", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is painted red on all faces, then cut into 27 equal smaller cubes. How many small cubes have exactly 2 red faces?",
    visual: "text",
    options: ["12", "8", "6", "10"], correct: 0,
    explanation: "Edge cubes (not corners) have 2 painted faces. A cube has 12 edges, each with 1 such cube = 12." },
  { id: "Y3SR8", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is painted red on all faces, then cut into 27 equal smaller cubes. How many small cubes have exactly 3 red faces?",
    visual: "text",
    options: ["8", "6", "12", "4"], correct: 0,
    explanation: "Only the corner cubes have 3 painted faces. A cube has 8 corners, so 8 cubes." },

  // --- New 18 (Y3SR9–Y3SR26) ---
  { id: "Y3SR9", category: "Spatial Reasoning", difficulty: 1,
    question: "How many faces does a rectangular prism (box shape) have?",
    visual: "text",
    options: ["6", "4", "8", "12"], correct: 0,
    explanation: "A rectangular prism has 6 faces: top, bottom, front, back, left, right." },
  { id: "Y3SR10", category: "Spatial Reasoning", difficulty: 1,
    question: "A cross-shaped net made of 6 identical squares is folded up. What 3D shape does it form?",
    visual: "text",
    options: ["Cube", "Rectangular prism", "Pyramid", "Cylinder"], correct: 0,
    explanation: "A cross-shaped net of 6 squares folds into a cube." },
  { id: "Y3SR11", category: "Spatial Reasoning", difficulty: 2,
    question: "A cube is painted blue on all faces, then cut into 64 smaller cubes (4×4×4). How many small cubes have exactly 3 blue faces?",
    visual: "text",
    options: ["8", "12", "6", "4"], correct: 0,
    explanation: "Corner cubes have 3 painted faces. A cube has 8 corners, regardless of how finely it is cut." },
  { id: "Y3SR12", category: "Spatial Reasoning", difficulty: 2,
    question: "A cube is painted blue on all faces, then cut into 64 smaller cubes (4×4×4). How many small cubes have exactly 2 blue faces?",
    visual: "text",
    options: ["24", "12", "16", "8"], correct: 0,
    explanation: "Edge cubes (not corners): 12 edges × 2 non-corner cubes per edge = 24." },
  { id: "Y3SR13", category: "Spatial Reasoning", difficulty: 2,
    question: "A cube is painted blue on all faces, then cut into 64 smaller cubes (4×4×4). How many small cubes have exactly 1 blue face?",
    visual: "text",
    options: ["24", "16", "12", "8"], correct: 0,
    explanation: "Face-center cubes: each face has (4−2)² = 4 such cubes. 6 faces × 4 = 24." },
  { id: "Y3SR14", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is painted blue on all faces, then cut into 64 smaller cubes (4×4×4). How many small cubes have NO blue face?",
    visual: "text",
    options: ["8", "0", "4", "12"], correct: 0,
    explanation: "Interior cubes form a (4−2)³ = 2³ = 8 cube inside." },
  { id: "Y3SR15", category: "Spatial Reasoning", difficulty: 2,
    question: "What cross-section do you get when you slice a cube exactly through the middle, parallel to one of its faces?",
    visual: "text",
    options: ["Square", "Rectangle", "Triangle", "Circle"], correct: 0,
    explanation: "A cut parallel to a face of a cube produces a square cross-section." },
  { id: "Y3SR16", category: "Spatial Reasoning", difficulty: 2,
    question: "If you cut a single corner off a cube with one straight cut, what shape is the new face created?",
    visual: "text",
    options: ["Triangle", "Square", "Pentagon", "Rectangle"], correct: 0,
    explanation: "Slicing off a corner of a cube cuts through three edges meeting at that corner, creating a triangular face." },
  { id: "Y3SR17", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is sliced by a plane through the midpoints of three edges that share a common vertex. What shape is the cross-section?",
    visual: "text",
    options: ["Equilateral triangle", "Square", "Regular hexagon", "Isosceles triangle"], correct: 0,
    explanation: "The three midpoints are equidistant from each other, forming an equilateral triangle." },
  { id: "Y3SR18", category: "Spatial Reasoning", difficulty: 3,
    question: "How many edges does a regular octahedron have?",
    visual: "text",
    options: ["12", "8", "10", "6"], correct: 0,
    explanation: "An octahedron has 8 faces, 6 vertices, and by Euler's formula (V−E+F=2): 6−E+8=2, so E=12." },
  { id: "Y3SR19", category: "Spatial Reasoning", difficulty: 2,
    question: "A cylinder is sliced perpendicular to its axis. What shape is the cross-section?",
    visual: "text",
    options: ["Circle", "Rectangle", "Oval", "Square"], correct: 0,
    explanation: "Cutting a cylinder perpendicular to its axis always gives a circle." },
  { id: "Y3SR20", category: "Spatial Reasoning", difficulty: 2,
    question: "If a cone is sliced by a plane parallel to its base, what shape is the cross-section?",
    visual: "text",
    options: ["Circle", "Oval", "Triangle", "Parabola"], correct: 0,
    explanation: "A plane parallel to the base of a cone produces a smaller circle." },
  { id: "Y3SR21", category: "Spatial Reasoning", difficulty: 3,
    question: "Four cubes are arranged in a 2×2 square (each touching its neighbors). How many unit faces are on the exterior?",
    visual: "text",
    options: ["16", "20", "18", "12"], correct: 0,
    explanation: "4 cubes have 24 faces total. 4 pairs of adjacent cubes each hide 2 faces. 24 − 8 = 16." },
  { id: "Y3SR22", category: "Spatial Reasoning", difficulty: 3,
    question: "How many faces does a regular dodecahedron have?",
    visual: "text",
    options: ["12", "10", "20", "8"], correct: 0,
    explanation: "Dodeca- means 12. A regular dodecahedron has 12 pentagonal faces." },
  { id: "Y3SR23", category: "Spatial Reasoning", difficulty: 2,
    question: "If you glue 4 cubes in a straight line (each sharing one face with the next), how many faces are exposed?",
    visual: "text",
    options: ["18", "16", "20", "22"], correct: 0,
    explanation: "4 × 6 = 24 total faces. 3 joints × 2 hidden faces = 6 hidden. 24 − 6 = 18." },
  { id: "Y3SR24", category: "Spatial Reasoning", difficulty: 3,
    question: "A cube is sliced by a plane passing through the midpoints of six edges (one on each face). What shape is the cross-section?",
    visual: "text",
    options: ["Regular hexagon", "Square", "Equilateral triangle", "Pentagon"], correct: 0,
    explanation: "Cutting through the midpoint of one edge per face creates a regular hexagon." },
  { id: "Y3SR25", category: "Spatial Reasoning", difficulty: 1,
    question: "How many faces does a hexagonal prism have?",
    visual: "text",
    options: ["8", "6", "10", "12"], correct: 0,
    explanation: "2 hexagonal ends + 6 rectangular sides = 8 faces." },
  { id: "Y3SR26", category: "Spatial Reasoning", difficulty: 3,
    question: "A 3×3×3 cube is painted on all faces. How many individual small-cube faces are painted in total?",
    visual: "text",
    options: ["54", "48", "27", "60"], correct: 0,
    explanation: "Each of the 6 big faces covers 9 small faces. 6 × 9 = 54 painted small-cube faces." },

  // =========================================================================
  // MATHEMATICAL PUZZLES  (26 questions — Y3MP1 … Y3MP26)
  // =========================================================================

  // --- Existing 8 (Y3MP1–Y3MP8) ---
  { id: "Y3MP1", category: "Mathematical Puzzles", difficulty: 1,
    question: "Three friends take 3 minutes to eat 3 sandwiches. How long would it take 9 friends to eat 9 sandwiches?",
    visual: "text",
    options: ["3 minutes", "9 minutes", "1 minute", "27 minutes"], correct: 0,
    explanation: "Each friend eats 1 sandwich in 3 minutes. 9 friends each eating 1 sandwich still takes 3 minutes." },
  { id: "Y3MP2", category: "Mathematical Puzzles", difficulty: 1,
    question: "A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball. How much does the ball cost?",
    visual: "text",
    options: ["$0.05", "$0.10", "$0.15", "$1.00"], correct: 0,
    explanation: "Let ball = x. Bat = x + 1. So x + (x+1) = 1.10. 2x = 0.10. x = $0.05." },
  { id: "Y3MP3", category: "Mathematical Puzzles", difficulty: 2,
    question: "Two fathers and two sons go fishing. Each catches one fish. They bring home 3 fish. How?",
    visual: "text",
    options: ["They are grandfather, father, and son", "One fish was thrown back", "Someone caught two fish", "It's not possible"],
    correct: 0, explanation: "There are only 3 people: grandfather, father (also a son), and grandson." },
  { id: "Y3MP4", category: "Mathematical Puzzles", difficulty: 2,
    question: "A clock shows 3:15. What is the angle between the hour and minute hands?",
    visual: "text",
    options: ["7.5°", "0°", "15°", "22.5°"], correct: 0,
    explanation: "At 3:15, the minute hand is at 90°. The hour hand is at 90° + 7.5° = 97.5°. Difference: 7.5°." },
  { id: "Y3MP5", category: "Mathematical Puzzles", difficulty: 2,
    question: "5 cats catch 5 mice in 5 minutes. How many cats are needed to catch 100 mice in 100 minutes?",
    visual: "text",
    options: ["5", "100", "20", "50"], correct: 0,
    explanation: "Each cat catches 1 mouse per 5 minutes. In 100 minutes, each cat catches 20 mice. 100/20 = 5 cats." },
  { id: "Y3MP6", category: "Mathematical Puzzles", difficulty: 3,
    question: "Find the missing number in the grid where each row follows the same rule.",
    visual: "number-grid", grid: [[2, 3, 12], [4, 5, 40], [3, 7, "?"]],
    options: ["42", "21", "30", "63"], correct: 0,
    explanation: "The rule is: col1 × col2 × 2 = col3. So 3 × 7 × 2 = 42." },
  { id: "Y3MP7", category: "Mathematical Puzzles", difficulty: 3,
    question: "Find the missing number in the grid where each row follows the same rule.",
    visual: "number-grid", grid: [[3, 4, 25], [5, 12, 169], [8, 6, "?"]],
    options: ["100", "48", "64", "14"], correct: 0,
    explanation: "The rule is: col1² + col2² = col3. So 8² + 6² = 64 + 36 = 100." },
  { id: "Y3MP8", category: "Mathematical Puzzles", difficulty: 3,
    question: "A lily pad doubles in size each day. It takes 48 days to cover the entire lake. On what day was it half-covered?",
    visual: "text",
    options: ["Day 47", "Day 24", "Day 36", "Day 46"], correct: 0,
    explanation: "Since it doubles daily, on day 47 it was half the size of day 48 — so half-covered on day 47." },

  // --- New 18 (Y3MP9–Y3MP26) ---
  { id: "Y3MP9", category: "Mathematical Puzzles", difficulty: 1,
    question: "If 8 workers build a wall in 6 hours, how long would 4 workers take to build the same wall?",
    visual: "text",
    options: ["12 hours", "3 hours", "8 hours", "24 hours"], correct: 0,
    explanation: "Total work = 8 × 6 = 48 worker-hours. With 4 workers: 48 ÷ 4 = 12 hours." },
  { id: "Y3MP10", category: "Mathematical Puzzles", difficulty: 1,
    question: "A number is multiplied by 3 and then 7 is added. The result is 22. What is the number?",
    visual: "text",
    options: ["5", "7", "4", "6"], correct: 0,
    explanation: "3x + 7 = 22. So 3x = 15, x = 5." },
  { id: "Y3MP11", category: "Mathematical Puzzles", difficulty: 2,
    question: "What is the angle between the hour and minute hands of a clock at 6:00?",
    visual: "text",
    options: ["180°", "120°", "90°", "150°"], correct: 0,
    explanation: "At 6:00 the hour hand points at 6 and the minute hand points at 12, exactly opposite: 180°." },
  { id: "Y3MP12", category: "Mathematical Puzzles", difficulty: 2,
    question: "Pipe A fills a tank in 6 hours, Pipe B fills it in 3 hours. How long do both together take?",
    visual: "text",
    options: ["2 hours", "3 hours", "4.5 hours", "1 hour"], correct: 0,
    explanation: "Rate A = 1/6, Rate B = 1/3. Combined = 1/6 + 2/6 = 3/6 = 1/2. Time = 2 hours." },
  { id: "Y3MP13", category: "Mathematical Puzzles", difficulty: 2,
    question: "A number doubled and then decreased by 5 gives 19. What is the number?",
    visual: "text",
    options: ["12", "7", "14", "10"], correct: 0,
    explanation: "2x − 5 = 19. 2x = 24. x = 12." },
  { id: "Y3MP14", category: "Mathematical Puzzles", difficulty: 2,
    question: "Two trains 300 km apart travel toward each other at 60 km/h and 90 km/h. When do they meet?",
    visual: "text",
    options: ["2 hours", "3 hours", "1.5 hours", "2.5 hours"], correct: 0,
    explanation: "Combined speed = 60 + 90 = 150 km/h. Time = 300 ÷ 150 = 2 hours." },
  { id: "Y3MP15", category: "Mathematical Puzzles", difficulty: 2,
    question: "The sum of three consecutive integers is 45. What is the largest?",
    visual: "text",
    options: ["16", "15", "17", "14"], correct: 0,
    explanation: "Let them be n−1, n, n+1. Sum = 3n = 45, so n = 15. Largest = 16." },
  { id: "Y3MP16", category: "Mathematical Puzzles", difficulty: 2,
    question: "A shopkeeper sells an item for $120, making a 20% profit. What was the cost price?",
    visual: "text",
    options: ["$100", "$96", "$110", "$80"], correct: 0,
    explanation: "Cost × 1.20 = 120. Cost = 120 ÷ 1.20 = $100." },
  { id: "Y3MP17", category: "Mathematical Puzzles", difficulty: 3,
    question: "What is the angle between the hour and minute hands at 3:30?",
    visual: "text",
    options: ["75°", "90°", "60°", "80°"], correct: 0,
    explanation: "Minute hand at 180°. Hour hand at 90° + 15° = 105°. Angle = 180° − 105° = 75°." },
  { id: "Y3MP18", category: "Mathematical Puzzles", difficulty: 3,
    question: "If A=1, B=2, C=3, …, Z=26, what is the sum of the letters in the word 'MATH'?",
    visual: "text",
    options: ["42", "40", "38", "44"], correct: 0,
    explanation: "M=13, A=1, T=20, H=8. Sum = 13 + 1 + 20 + 8 = 42." },
  { id: "Y3MP19", category: "Mathematical Puzzles", difficulty: 3,
    question: "A jar has 3 red and 5 blue marbles. If you pick one at random, what is the probability it is red?",
    visual: "text",
    options: ["3/8", "5/8", "1/2", "3/5"], correct: 0,
    explanation: "Total marbles = 8. P(red) = 3/8." },
  { id: "Y3MP20", category: "Mathematical Puzzles", difficulty: 2,
    question: "A rope is cut into 3 pieces. The 2nd is twice as long as the 1st, and the 3rd is three times as long as the 1st. If the rope is 60 cm, how long is the shortest piece?",
    visual: "text",
    options: ["10 cm", "15 cm", "12 cm", "20 cm"], correct: 0,
    explanation: "x + 2x + 3x = 60. 6x = 60. x = 10 cm." },
  { id: "Y3MP21", category: "Mathematical Puzzles", difficulty: 3,
    question: "If you flip a fair coin three times, what is the probability of getting exactly two heads?",
    visual: "text",
    options: ["3/8", "1/2", "1/4", "1/8"], correct: 0,
    explanation: "Total outcomes = 8. Favorable (HHT, HTH, THH) = 3. P = 3/8." },
  { id: "Y3MP22", category: "Mathematical Puzzles", difficulty: 3,
    question: "In a grid where each cell equals its row number × its column number, what is the value in row 5, column 7?",
    visual: "text",
    options: ["35", "12", "57", "30"], correct: 0,
    explanation: "Row 5 × Column 7 = 5 × 7 = 35." },
  { id: "Y3MP23", category: "Mathematical Puzzles", difficulty: 2,
    question: "The average of 5 numbers is 12. If one number is removed, the average of the remaining 4 is 10. What was removed?",
    visual: "text",
    options: ["20", "12", "15", "24"], correct: 0,
    explanation: "Total = 5 × 12 = 60. Remaining total = 4 × 10 = 40. Removed = 60 − 40 = 20." },
  { id: "Y3MP24", category: "Mathematical Puzzles", difficulty: 3,
    question: "A rectangle's length is 3 times its width. If the perimeter is 48 cm, what is the area?",
    visual: "text",
    options: ["108 cm²", "144 cm²", "72 cm²", "96 cm²"], correct: 0,
    explanation: "2(3w + w) = 48 → 8w = 48 → w = 6, length = 18. Area = 18 × 6 = 108 cm²." },
  { id: "Y3MP25", category: "Mathematical Puzzles", difficulty: 3,
    question: "A bat and a ball cost $2.10. The bat costs $2.00 more than the ball. How much does the ball cost?",
    visual: "text",
    options: ["$0.05", "$0.10", "$0.15", "$0.20"], correct: 0,
    explanation: "Let ball = x. Bat = x + 2. So 2x + 2 = 2.10. 2x = 0.10. x = $0.05." },
  { id: "Y3MP26", category: "Mathematical Puzzles", difficulty: 3,
    question: "Find the missing number where each row's rule is: col3 = (col1 + col2)².",
    visual: "number-grid", grid: [[1, 2, 9], [2, 3, 25], [3, 4, "?"]],
    options: ["49", "36", "64", "12"], correct: 0,
    explanation: "(1+2)² = 9, (2+3)² = 25, (3+4)² = 7² = 49." }
];
