# -*- coding: utf-8 -*-
"""Mechanical English → Romanian fixes for ro-train-adult.js (TPR/TNR hints & explanations)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "lang"
RO = ROOT / "ro-train-adult.js"


def main() -> None:
    text = RO.read_text(encoding="utf-8")
    # Order: longer / more specific first where it matters
    reps: list[tuple[str, str]] = [
        ("The next term is ", "Următorul termen este "),
        ("The next difference is ", "Următoarea diferență este "),
        ("Next difference is ", "Următoarea diferență este "),
        (" so next difference is ", " deci următoarea diferență este "),
        (" so next is ", " deci următorul termen este "),
        ("Differences are ", "Diferențele sunt "),
        ("The differences are ", "Diferențele sunt "),
        ("The differences între terms", "Diferențele dintre termeni"),
        ("The differences între terms increase by 1 la fiecare pas", "Diferențele dintre termeni cresc cu 1 la fiecare pas"),
        ("The sequence lists ", "Șirul listează "),
        ("The sequence alternates între two operations", "Șirul alternează între două operații"),
        ("The sequence alternates ", "Șirul alternează "),
        ("Each term follows the rule: ", "Fiecare termen respectă regula: "),
        ("Each term = ", "Fiecare termen = "),
        ("Each term equals ", "Fiecare termen este egal cu "),
        ("Each term uses ", "Fiecare termen folosește "),
        ("Each term depends on ", "Fiecare termen depinde de "),
        ("Each term is the sum of the two preceding terms", "Fiecare termen este suma celor doi termeni precedenți"),
        ("Fiecare termen este the sum of the two preceding terms", "Fiecare termen este suma celor doi termeni precedenți"),
        ("Each fold doubles ", "Fiecare pliere dublează "),
        ("Each fold in half doubles ", "Fiecare pliere în jumătate dublează "),
        ("Each cat catches ", "Fiecare pisică prinde "),
        ("Each machine makes ", "Fiecare mașină produce "),
        ("Each worker builds ", "Fiecare muncitor construiește "),
        ("Each person paints ", "Fiecare persoană pictează "),
        ("Each full day-night cycle", "Fiecare ciclu zi-noapte complet"),
        ("Each of the 6 original fețe", "Fiecare dintre cele 6 fețe originale"),
        ("Each corner cube has exact ", "Fiecare cub de colț are exact "),
        ("Each pyramid contributes ", "Fiecare piramidă contribuie cu "),
        ("Each triangular base contributes ", "Fiecare bază triunghiulară aduce "),
        ("Try doubling the previous term și adding a small constant", "Încearcă să dublezi termenul anterior și să aduni o constantă mică"),
        ("Try doubling the previous term și subtracting a small constant", "Încearcă să dublezi termenul anterior și să scazi o constantă mică"),
        ("Try multiplying the previous term by 3 și adjusting", "Încearcă să înmulțești termenul anterior cu 3 și să ajustezi"),
        ("Multiply the previous term by a number și add a constant", "Înmulțește termenul anterior cu un număr și adună o constantă"),
        ("Multiply the previous term by a number și subtract a constant", "Înmulțește termenul anterior cu un număr și scade o constantă"),
        ("Double the previous term și add a constant to get the next", "Dublează termenul anterior și adună o constantă pentru următorul"),
        ("Double the previous term și make a small adjustment", "Dublează termenul anterior și fă o mică ajustare"),
        ("Double the previous term și add a constant la fiecare pas", "Dublează termenul anterior și adună o constantă la fiecare pas"),
        ("Compute the differences între terms. Do those differences form a pattern?", "Calculează diferențele dintre termeni. Aceste diferențe formează un tipar?"),
        ("Compute the differences între terms. Do those differences remind you of a famous sequence?", "Calculează diferențele dintre termeni. Îți amintesc aceste diferențe de un șir celebru?"),
        ("Compute the differences, apoi check if those differences increase in a regular way", "Calculează diferențele, apoi verifică dacă aceste diferențe cresc regulat"),
        ("Compute the differences. They increase by 1 each time — a hallmark of triangular numbers", "Calculează diferențele. Ele cresc cu 1 de fiecare dată — semnul numerelor triunghiulare"),
        (" increasing by 2 la fiecare pas. The next difference is 10, so ", " crescând cu 2 la fiecare pas. Următoarea diferență este 10, deci "),
        (" increasing by 3 la fiecare pas. The next difference is 15, so ", " crescând cu 3 la fiecare pas. Următoarea diferență este 15, deci "),
        (" increasing by 4 la fiecare pas. The next difference is 20, so ", " crescând cu 4 la fiecare pas. Următoarea diferență este 20, deci "),
        (" increasing by 5 la fiecare pas. The next difference is 25, so ", " crescând cu 5 la fiecare pas. Următoarea diferență este 25, deci "),
        (" — increasing by 2 la fiecare pas. The next difference is 10, so ", " — crescând cu 2 la fiecare pas. Următoarea diferență este 10, deci "),
        (" — increasing by 3 la fiecare pas. The next difference is 15, so ", " — crescând cu 3 la fiecare pas. Următoarea diferență este 15, deci "),
        (" — consecutive odd numbers. The next difference is 9, so ", " — numere impare consecutive. Următoarea diferență este 9, deci "),
        (" — perfect squares (1², 2², 3², 4²). The next difference is 5²=25, so ", " — pătrate perfecte (1², 2², 3², 4²). Următoarea diferență este 5²=25, deci "),
        (" — these are factorials (1!, 2!, 3!, 4!). The next difference is 5!=120, so ", " — acestea sunt factoriali (1!, 2!, 3!, 4!). Următoarea diferență este 5!=120, deci "),
        (" — triangular numbers. The next triangular number is 15, so ", " — numere triunghiulare. Următorul număr triunghiular este 15, deci "),
        (" — powers of 2: 2, 4, 8, 16. The next difference is 32, so ", " — puteri ale lui 2: 2, 4, 8, 16. Următoarea diferență este 32, deci "),
        ("The differences are 4, 7, 10, 13 — an arithmetic sequence with step 3", "Diferențele sunt 4, 7, 10, 13 — o progresie aritmetică cu pasul 3"),
        ("The differences are 5, 9, 13, 17 — increasing by 4. Acestea sunt hexagonal numbers", "Diferențele sunt 5, 9, 13, 17 — cresc cu 4. Acestea sunt numere hexagonale"),
        ("The differences are 12, 24, 36, 48 — multiples of 12", "Diferențele sunt 12, 24, 36, 48 — multipli de 12"),
        ("The differences are 6, 12, 18, 24 — multiples of 6", "Diferențele sunt 6, 12, 18, 24 — multipli de 6"),
        ("The operations alternate între two different rules at odd și even steps", "Operațiile alternează între două reguli diferite la pași impari și pari"),
        ("Two different operations alternate. One adds, the other multiplies", "Două operații diferite alternează. Una adună, cealaltă înmulțește"),
        ("Try expressing each term as ", "Încearcă să exprimi fiecare termen ca "),
        ("Try expressing each term as the sum of a square și a power of 2", "Încearcă să exprimi fiecare termen ca sumă dintre un pătrat și o putere a lui 2"),
        ("Try expressing each term as a power of 3 minus 1", "Încearcă să exprimi fiecare termen ca o putere a lui 3 minus 1"),
        ("Try expressing each term as n² minus something", "Încearcă să exprimi fiecare termen ca n² minus ceva"),
        ("Try expressing each term as 2n² for consecutive values of n", "Încearcă să exprimi fiecare termen ca 2n² pentru valori consecutive ale lui n"),
        ("Try expressing each term as n²(n + 1)", "Încearcă să exprimi fiecare termen ca n²(n + 1)"),
        ("Try expressing each term as a product of two numbers close together", "Încearcă să exprimi fiecare termen ca produsul a două numere apropiate"),
        ("Try dividing each term by 2. Do the results look familiar?", "Încearcă să împarți fiecare termen la 2. Rezultatele îți par familiare?"),
        ("Try dividing each term by 2. Do the results look like factorials?", "Încearcă să împarți fiecare termen la 2. Rezultatele seamănă cu factoriali?"),
        ("Scade 1 from each term. Do the results look familiar?", "Scade 1 din fiecare termen. Rezultatele îți par familiare?"),
        ("Adună 1 to each term. What well-known sequence do you get?", "Adună 1 la fiecare termen. Ce șir cunoscut obții?"),
        ("Scade 1 from each term. What kind of numbers remain?", "Scade 1 din fiecare termen. Ce fel de numere rămân?"),
        ("Scade 3 from each term. What sequence do you recognize?", "Scade 3 din fiecare termen. Ce șir recunoști?"),
        ("Scade 1 from each term și see if you recognize those numbers", "Scade 1 din fiecare termen și vezi dacă recunoști aceste numere"),
        ("Adună 1 to each term. Do you recognize the resulting numbers?", "Adună 1 la fiecare termen. Recunoști numerele rezultate?"),
        ("The differences între terms increase by a constant. Găsește that constant", "Diferențele dintre termeni cresc cu o constantă. Găsește acea constantă"),
        ("The differences între terms are consecutive odd numbers", "Diferențele dintre termeni sunt numere impare consecutive"),
        ("The differences între terms are perfect squares. Sum up consecutive squares", "Diferențele dintre termeni sunt pătrate perfecte. Adună pătrate consecutive"),
        ("The differences între terms are triangular numbers: 1, 3, 6, 10, …", "Diferențele dintre termeni sunt numere triunghiulare: 1, 3, 6, 10, …"),
        ("Găsește diferențele dintre termeni. Sunt aceste diferențe un șir cunoscut?", "Găsește diferențele dintre termeni. Sunt aceste diferențe un șir cunoscut?"),  # noop if same
        ("Sunt consecutive prime numbers starting from 5. The next prime after 17 is 19", "Sunt numere prime consecutive începând de la 5. Următorul prim după 17 este 19"),
        ("Sunt consecutive prime numbers starting from 11. The next prime after 23 is 29", "Sunt numere prime consecutive începând de la 11. Următorul prim după 23 este 29"),
        ("Fiecare termen este a perfect square. Care squares are these?", "Fiecare termen este un pătrat perfect. Despre ce pătrate e vorba?"),
        ("Fiecare termen este a fraction of the previous. What divisor is used?", "Fiecare termen este o fracțiune din cel anterior. Ce divizor se folosește?"),
        ("Each term gains an extra zero. What multiplier does that?", "Fiecare termen câștigă un zero în plus. Ce înmulțitor corespunde?"),
        ("Try doubling a term și apoi adjusting by a small number to get the next", "Încearcă să dublezi un termen și apoi să ajustezi cu un număr mic pentru următorul"),
        ("Ce fracție of the previous term gives the current term?", "Ce fracțiune din termenul anterior dă termenul curent?"),
        ("Cât este the ratio între consecutive terms?", "Care este raportul dintre termenii consecutivi?"),
        ("Cu cât se scade each time?", "Cu cât se scade de fiecare dată?"),
        ("Cu cât se scade each step? That amount grows", "Cu cât se scade la fiecare pas? Această mărime crește"),
        ("How does column 3 relate to columns 1 și 2?", "Cum se leagă coloana 3 de coloanele 1 și 2?"),
        ("Look at how each row relates to its first number", "Uită-te cum se leagă fiecare rând de primul său număr"),
        ("Sunt consecutive even numbers starting from 0", "Sunt numere pare consecutive începând de la 0"),
        ("Each group follows the pattern: letter, next letter, same first letter — deplasat cu un pas la fiecare grup", "Fiecare grup urmează tiparul: literă, litera următoare, aceeași primă literă — deplasat cu un pas la fiecare grup"),
        ("The amount subtracted increases by 1 each step", "Cantitatea scăzută crește cu 1 la fiecare pas"),
        ("Numerele are decreasing by a fixed amount", "Numerele scad cu o cantitate fixă"),
        ("Cât este each number a multiple of?", "Fiecare număr este multiplu al cui?"),
        ("Fiecare termen este tripled și apoi increased by 1", "Fiecare termen se triplează și apoi se mărește cu 1"),
        ("Fiecare termen este înmulțit cu 4 și decreased by 1", "Fiecare termen se înmulțește cu 4 și apoi se micșorează cu 1"),
        ("Acestea sunt primes listed in descending order", "Acestea sunt numere prime listate în ordine descrescătoare"),
        ("The sequence lists consecutive primes in reverse order", "Șirul listează numere prime consecutive în ordine inversă"),
        ("Tiparul alternează +1 and ×2", "Tiparul alternează +1 și ×2"),
        ("Row pattern is n¹, n², n³", "Tiparul rândului este n¹, n², n³"),
        ("First differences:", "Diferențe de ordinul I:"),
        ("Second differences:", "Diferențe de ordinul II:"),
        ("Next first difference:", "Următoarea diferență de ordinul I:"),
        ("Answer:", "Răspuns:"),
        ("Like Fibonacci: each term = sum of previous two", "Ca la Fibonacci: fiecare termen = suma celor doi precedenți"),
        ("Try multiplying each term by 4 și adding 1", "Încearcă să înmulțești fiecare termen cu 4 și să aduni 1"),
        ("Each column uses an odd power of the first number", "Fiecare coloană folosește o putere impară a primului număr"),
        ("Fiecare termen este twice a prime number. Care primes?", "Fiecare termen este de două ori un număr prim. Care prime?"),
        ("Șirul este 7², 6², 5², 4², 3², so next is 2² = 4", "Șirul este 7², 6², 5², 4², 3², deci următorul este 2² = 4"),
        ("Șirul este 1⁴, 2⁴, 3⁴, 4⁴, so next is 5⁴ = 625", "Șirul este 1⁴, 2⁴, 3⁴, 4⁴, deci următorul este 5⁴ = 625"),
        ("Acestea sunt cubes of consecutive odd numbers", "Acestea sunt cuburi ale numerelor impare consecutive"),
        ("Acestea sunt squares of cumulative sums", "Acestea sunt pătrate ale sumelor cumulative"),
        ("Acestea sunt squares of consecutive even numbers", "Acestea sunt pătrate ale numerelor pare consecutive"),
        ("Acestea sunt squares of consecutive odd numbers", "Acestea sunt pătrate ale numerelor impare consecutive"),
        ("Acestea sunt triangular numbers. The differences între terms increase by 1 la fiecare pas", "Acestea sunt numere triunghiulare. Diferențele dintre termeni cresc cu 1 la fiecare pas"),
        ("Acestea sunt triangular numbers T(5) through T(10)", "Acestea sunt numere triunghiulare T(5) până la T(10)"),
        ("Acestea sunt triangular numbers T(8) through T(13)", "Acestea sunt numere triunghiulare T(8) până la T(13)"),
        ("For n=6:", "Pentru n=6:"),
        ("Pentagonal numbers:", "Numere pentagonale:"),
        ("Tetrahedral numbers:", "Numere tetraedrice:"),
        ("Acestea sunt the Catalan numbers", "Acestea sunt numerele Catalan"),
        ("Think about what power each position's base is raised to", "Gândește-te la ce putere este ridicată baza fiecărei poziții"),
        ("Fiecare termen este n raised to the power (n−1):", "Fiecare termen este n ridicat la puterea (n−1):"),
        ("Express each term as a difference of two exponential values", "Exprimă fiecare termen ca diferență a două valori exponențiale"),
        ("Try splitting each term into a cube part și a linear part", "Încearcă să descompui fiecare termen într-o parte cubică și una liniară"),
        ("Try splitting each term into a factorial part și a square part", "Încearcă să descompui fiecare termen într-o parte factorială și una pătratică"),
        ("Try factoring each term into n² times something", "Încearcă să factorizezi fiecare termen în n² ori ceva"),
        ("Think about powers of 2, apoi subtract something that depends on the position", "Gândește-te la puteri ale lui 2, apoi scade ceva ce depinde de poziție"),
        ("Each term uses both of the two preceding terms with different weights", "Fiecare termen folosește ambii termeni precedenți cu ponderi diferite"),
        ("So 22 + 3 = 25", "Deci 22 + 3 = 25"),
        ("So 17 × 2 = 34", "Deci 17 × 2 = 34"),
        ("Rândul 3 starts at 3:", "Rândul 3 începe la 3:"),
        ("Tiparul alternează ○ and ■", "Tiparul alternează ○ și ■"),
        ("Pairs of shapes alternate", "Perechile de forme alternează"),
        ("Fiecare termen este a doubled consecutive letter", "Fiecare termen este o literă consecutivă dublată"),
        ("Numerele decrease by a fixed amount", "Numerele scad cu o cantitate fixă"),
        ("Numerele decrease by a constant", "Numerele scad cu o constantă"),
        ("Steating with 1, one fold gives 2 layers", "Pornind de la 1, o pliere dă 2 straturi"),
        ("The prefix 'penta-' refers to a specific number", "Prefixul „penta-” se referă la un număr anume"),
        ("The prefix 'hexa-' means a number — think of hexadecimal", "Prefixul „hexa-” indică un număr — gândește-te la șase (șase laturi)"),
        ("The prefix 'tri-' tells you the answer directly", "Prefixul „tri-” îți dă direct răspunsul"),
        ("The name tells you: 'tri' means three", "Numele spune: „tri” înseamnă trei"),
    ]
    for old, new in reps:
        text = text.replace(old, new)
    RO.write_text(text, encoding="utf-8")
    print("bulk replacements applied:", len(reps))


if __name__ == "__main__":
    main()
