# -*- coding: utf-8 -*-
"""Full Romanian strings for training logic exercises 8–11 (merges into ro-train-8-11.js)."""
TLR811_RO: dict[str, tuple[str, str, list[str], str]] = {
    "TLR811_1_01": (
        "Toți câinii sunt animale. Spot este un câine. Ce este Spot?",
        "Dacă Spot este câine și toți câinii sunt animale…",
        ["O plantă", "Un animal", "O pasăre", "Un pește"],
        "Toți câinii sunt animale. Spot este câine. Deci Spot este un animal.",
    ),
    "TLR811_1_02": (
        "Toate merele sunt fructe. Toate fructele sunt mâncare. Rezultă că toate merele sunt mâncare?",
        "Urmează lanțul: mere → fructe → mâncare.",
        ["Da", "Nu", "Doar unele", "Nu putem ști"],
        "Merele sunt fructe, iar fructele sunt mâncare. Deci toate merele sunt mâncare.",
    ),
    "TLR811_1_03": (
        "Tom este mai înalt decât Sam. Sam este mai înalt decât Ben. Cine este cel mai înalt?",
        "Pune-i în ordinea înălțimii.",
        ["Sam", "Ben", "Tom", "Sunt la fel"],
        "Tom > Sam > Ben. Tom este cel mai înalt.",
    ),
    "TLR811_1_04": (
        "Toate pisicile au coadă. Mustăți este o pisică. Are Mustăți coadă?",
        "Dacă toate pisicile au coadă și Mustăți este pisică…",
        ["Da", "Nu", "Poate", "Doar uneori"],
        "Toate pisicile au coadă. Mustăți este pisică. Deci Mustăți are coadă.",
    ),
    "TLR811_1_05": (
        "Ana este mai în vârstă decât Ben. Ben este mai în vârstă decât Cara. Cine este cea mai tânără?",
        "Ordonează-i de la cel mai bătrân la cel mai tânăr.",
        ["Ana", "Ben", "Cara", "Au aceeași vârstă"],
        "Ana > Ben > Cara ca vârstă. Cara este cea mai tânără.",
    ),
    "TLR811_1_06": (
        "Toate păsările au pene. O rândunică este o pasăre. Are rândunica pene?",
        "Dacă toate păsările au pene…",
        ["Nu", "Da", "Doar iarna", "Poate"],
        "Toate păsările au pene. Rândunica este pasăre. Deci are pene.",
    ),
    "TLR811_1_07": (
        "Roșu este mai mare decât Albastru. Albastru este mai mare decât Verde. Care este cel mai mic?",
        "Ordonează-le după mărime.",
        ["Roșu", "Albastru", "Verde", "Sunt egale"],
        "Roșu > Albastru > Verde. Verde este cel mai mic.",
    ),
    "TLR811_1_08": (
        "Toți peștii trăiesc în apă. Un pește-auriu este pește. Unde trăiește un pește-auriu?",
        "Dacă toți peștii trăiesc în apă…",
        ["Pe uscat", "În copaci", "În apă", "În cer"],
        "Toți peștii trăiesc în apă. Peștele-auriu este pește. Deci trăiește în apă.",
    ),
    "TLR811_1_09": (
        "Cartea A are mai multe pagini decât cartea B. Cartea B are mai multe pagini decât cartea C. Care are cele mai puține pagini?",
        "Ordonează cărțile după numărul de pagini.",
        ["Cartea A", "Cartea B", "Cartea C", "Sunt egale"],
        "A > B > C la pagini. Cartea C are cele mai puține pagini.",
    ),
    "TLR811_1_10": (
        "Toate pătratele au 4 laturi. Această formă este un pătrat. Câte laturi are?",
        "Dacă este pătrat…",
        ["3", "4", "5", "6"],
        "Toate pătratele au 4 laturi. Această formă este pătrat. Deci are 4 laturi.",
    ),
    "TLR811_1_11": (
        "Pizza este mai ieftină decât friptura. Friptura este mai ieftină decât homarul. Care este cel mai ieftin?",
        "Ordonează-le după preț.",
        ["Friptura", "Homarul", "Pizza", "Costă la fel"],
        "Pizza < Friptura < Homar la preț. Pizza este cea mai ieftină.",
    ),
    "TLR811_1_12": (
        "Toți trandafirii sunt flori. Toate florile sunt plante. Este trandafirul o plantă?",
        "Urmează lanțul: trandafiri → flori → plante.",
        ["Da", "Nu", "Poate", "Doar trandafirii roșii"],
        "Trandafirii sunt flori, iar florile sunt plante. Deci trandafirul este plantă.",
    ),
    "TLR811_1_13": (
        "Echipa A a marcat mai mult decât echipa B. Echipa B a marcat mai mult decât echipa C. Cine a marcat cel mai mult?",
        "Clasifică echipele după scor.",
        ["Echipa C", "Echipa B", "Echipa A", "Egalitate"],
        "A > B > C la scor. Echipa A a marcat cel mai mult.",
    ),
    "TLR811_1_14": (
        "Toate monedele sunt rotunde. Un penny este o monedă. Ce formă are un penny?",
        "Dacă toate monedele sunt rotunde…",
        ["Pătrat", "Triunghi", "Rotundă", "Ovală"],
        "Toate monedele sunt rotunde. Penny-ul este monedă. Deci este rotundă.",
    ),
    "TLR811_1_15": (
        "Mia aleargă mai repede decât Lily. Lily aleargă mai repede decât Zoe. Cine este cea mai lentă?",
        "Clasifică-le după viteză.",
        ["Mia", "Lily", "Zoe", "Sunt la fel"],
        "Mia > Lily > Zoe la viteză. Zoe este cea mai lentă.",
    ),
    "TLR811_1_16": (
        "Toate triunghiurile au 3 laturi. Această formă are 3 laturi. Poate fi triunghi?",
        "Triunghiurile au 3 laturi. Înseamnă asta neapărat că forma este triunghi?",
        ["Da, poate fi", "Nu, niciodată", "Doar dacă e mare", "Doar dacă e roșu"],
        "Toate triunghiurile au 3 laturi, iar această formă are 3 laturi, deci poate fi triunghi.",
    ),
    "TLR811_1_17": (
        "Un elefant este mai greu decât un cal. Un cal este mai greu decât un câine. Care este cel mai ușor?",
        "Clasifică-le după greutate.",
        ["Elefantul", "Calul", "Câinele", "Cântăresc la fel"],
        "Elefant > Cal > Câine la greutate. Câinele este cel mai ușor.",
    ),
    "TLR811_1_18": (
        "Toate creioanele pot scrie. Acesta este un creion. Poate scrie?",
        "Dacă toate creioanele pot scrie…",
        ["Da", "Nu", "Doar uneori", "Nu știm"],
        "Toate creioanele pot scrie. Acesta este creion. Deci poate scrie.",
    ),
    "TLR811_1_19": (
        "Cutia A este mai lată decât cutia B. Cutia B este mai lată decât cutia C. Care este cea mai lată?",
        "Clasifică cutiile după lățime.",
        ["Cutia C", "Cutia B", "Cutia A", "Sunt la fel"],
        "A > B > C la lățime. Cutia A este cea mai lată.",
    ),
    "TLR811_1_20": (
        "Toată înghețata este rece. Aceasta este înghețată. Este rece?",
        "Dacă toată înghețata este rece…",
        ["Nu", "Poate", "Da", "Doar iarna"],
        "Toată înghețata este rece. Aceasta este înghețată. Deci este rece.",
    ),
    "TLR811_2_01": (
        "Toată ciocolata este dulce. Această bomboană este dulce. Este SIGUR ciocolată?",
        "Numai pentru că toată ciocolata e dulce, înseamnă că tot ce e dulce e ciocolată?",
        ["Da, sigur", "Nu, nu neapărat", "Doar ciocolata neagră", "Mereu"],
        "Toată ciocolata e dulce, dar și alte lucruri pot fi dulci. Nu e neapărat ciocolată.",
    ),
    "TLR811_2_02": (
        "Anna este mai înaltă decât Ben. Ben este mai înalt decât Cara. Cara este mai înaltă decât Dan. Cine este a doua ca înălțime?",
        "Pune-i pe toți patru în ordinea înălțimii.",
        ["Anna", "Ben", "Cara", "Dan"],
        "Anna > Ben > Cara > Dan. Ben este al doilea ca înălțime.",
    ),
    "TLR811_2_03": (
        "Toate mașinile au roți. Acest vehicul are roți. Este SIGUR o mașină?",
        "Doar mașinile au roți?",
        ["Da", "Nu, nu neapărat", "Doar dacă e roșie", "Mereu"],
        "Multe vehicule au roți (biciclete, autobuze, camioane). Nu e neapărat mașină.",
    ),
    "TLR811_2_04": (
        "Roșu este mai mare decât Albastru. Albastru este mai mare decât Verde. Verde este mai mare decât Galben. Care este al treilea ca mărime?",
        "Clasifică-le pe toate patru după mărime.",
        ["Roșu", "Albastru", "Verde", "Galben"],
        "Roșu > Albastru > Verde > Galben. Verde este al treilea ca mărime.",
    ),
    "TLR811_2_05": (
        "Toate pătratele sunt dreptunghiuri. Această formă este dreptunghi. Este SIGUR pătrat?",
        "Toate pătratele sunt dreptunghiuri, dar toate dreptunghiurile sunt pătrate?",
        ["Da", "Nu, nu neapărat", "Doar dacă e mic", "Mereu"],
        "Toate pătratele sunt dreptunghiuri, dar nu toate dreptunghiurile sunt pătrate. Poate să nu fie pătrat.",
    ),
    "TLR811_2_06": (
        "Kim a luat 90 de puncte. Lee 85. Min 95. Pat 80. Cine a fost al doilea?",
        "Clasifică de la cel mai mare scor la cel mai mic.",
        ["Kim", "Lee", "Min", "Pat"],
        "Min (95) > Kim (90) > Lee (85) > Pat (80). Kim a fost al doilea.",
    ),
    "TLR811_2_07": (
        "Toți câinii latră. Un animal latră. Este SIGUR câine?",
        "Doar câinii latră?",
        ["Da, sigur", "Nu, nu neapărat", "Doar câinii mari latră", "Mereu"],
        "Și alte animale pot lătra (ex. focile). Nu e neapărat câine.",
    ),
    "TLR811_2_08": (
        "Cartea A are 200 de pagini. B are 150. C are 300. D are 250. Care este a treia ca lungime?",
        "Ordonează de la cele mai multe pagini la cele mai puține.",
        ["Cartea A", "Cartea B", "Cartea C", "Cartea D"],
        "C (300) > D (250) > A (200) > B (150). Cartea A este a treia ca lungime.",
    ),
    "TLR811_2_09": (
        "Toate numerele pare se împart exact la 2. Numărul 15 nu se împarte exact la 2. Ce putem spune despre 15?",
        "Dacă nu se împarte la 2, poate fi par?",
        ["Este par", "Nu este par", "Nu putem ști", "Poate fi par"],
        "Toate numerele pare se împart la 2. 15 nu se împarte la 2. Deci 15 nu este par.",
    ),
    "TLR811_2_10": (
        "Amy, Ben, Cat și Dan aleargă. Amy îl întrece pe Ben. Cat o întrece pe Amy. Dan o întrece pe Cat. Cine câștigă?",
        "Dacă Dan o întrece pe Cat, iar Cat pe Amy…",
        ["Amy", "Ben", "Cat", "Dan"],
        "Dan > Cat > Amy > Ben. Dan câștigă.",
    ),
    "TLR811_2_11": (
        "Toate bicicletele au 2 roți. Acest vehicul are 2 roți. Este SIGUR bicicletă?",
        "Doar bicicletele au 2 roți?",
        ["Da", "Nu, nu neapărat", "Doar mountain bike-uri", "Mereu"],
        "Și trotinetele, motocicletele au 2 roți. Nu e neapărat bicicletă.",
    ),
    "TLR811_2_12": (
        "Patru prieteni au scoruri diferite: 70, 80, 90, 100. James a luat mai mult de 80 dar mai puțin de 100. Care a fost scorul lui?",
        "Care scor e între 80 și 100?",
        ["70", "80", "90", "100"],
        "Singurul scor între 80 și 100 este 90.",
    ),
    "TLR811_2_13": (
        "Toți păianjenii au 8 picioare. Această creatură are 8 picioare. Este SIGUR păianjen?",
        "Doar păianjenii au 8 picioare?",
        ["Da", "Nu, nu neapărat", "Doar cei mari", "Mereu"],
        "Și scorpionii au 8 picioare. 8 picioare nu înseamnă neapărat păianjen.",
    ),
    "TLR811_2_14": (
        "Stejarul este mai înalt decât mesteacănul. Pinul este mai înalt decât stejarul. Ulmul este mai scund decât mesteacănul. Care copac este cel mai înalt?",
        "Ordonează toți cei patru copaci.",
        ["Stejarul", "Mesteacănul", "Pinul", "Ulmul"],
        "Pin > Stejar > Mesteacăn > Ulm. Pinul este cel mai înalt.",
    ),
    "TLR811_2_15": (
        "Toate planetele orbitează în jurul unei stele. Pământul orbitează o stea. Dovedește asta că Pământul este planetă?",
        "Doar planetele orbitează stele?",
        ["Da, o dovedește", "Nu, nu o dovedește", "Doar uneori", "Mereu"],
        "Și cometele, asteroizii orbitează stele. Orbita singură nu dovedește că e planetă.",
    ),
    "TLR811_2_16": (
        "Sam are mai multe abțibilduri decât Mia. Mia are mai multe decât Jo. Jo are mai multe decât Lee. Cine are cele mai puține?",
        "Ordonează-i.",
        ["Sam", "Mia", "Jo", "Lee"],
        "Sam > Mia > Jo > Lee. Lee are cele mai puține.",
    ),
    "TLR811_2_17": (
        "Dacă plouă, solul este ud. Solul este ud. Plouă SIGUR?",
        "Solul ar putea fi ud și din alte motive?",
        ["Da, sigur", "Nu, nu neapărat", "Doar vara", "Mereu"],
        "Cineva ar fi putut uda cu furtunul. Solul ud nu dovedește ploaia.",
    ),
    "TLR811_2_18": (
        "Pisica cântărește mai puțin decât câinele. Câinele mai puțin decât oaia. Oaia mai puțin decât vaca. Care animal cântărește cel mai mult?",
        "Clasifică după greutate.",
        ["Pisica", "Câinele", "Oaia", "Vaca"],
        "Pisică < Câine < Oaie < Vacă. Vaca cântărește cel mai mult.",
    ),
    "TLR811_2_19": (
        "Toate merele sunt fructe. Acesta NU este fruct. Poate fi măr?",
        "Dacă toate merele sunt fructe, iar acesta nu e fruct…",
        ["Da", "Nu, nu poate", "Poate", "Doar cele verzi"],
        "Toate merele sunt fructe. Dacă nu e fruct, nu poate fi măr.",
    ),
    "TLR811_2_20": (
        "Patru copii au vârstele 8, 9, 10, 11 ani. Kai este mai mare decât Zoe. Zoe decât Leo. Leo decât Ivy. Câți ani are Zoe?",
        "Kai e cel mai mare, apoi Zoe, Leo, Ivy.",
        ["8", "9", "10", "11"],
        "Kai=11, Zoe=10, Leo=9, Ivy=8. Zoe are 10 ani.",
    ),
    "TLR811_3_01": (
        "Dacă plouă, Tom ia umbrelă. Dacă ia umbrelă, rămâne uscat. Plouă. Va rămâne Tom uscat?",
        "Urmează lanțul: ploaie → umbrelă → uscat.",
        ["Da", "Nu", "Poate", "Doar dacă e frig"],
        "Ploaie → umbrelă → uscat. Plouă, deci Tom rămâne uscat.",
    ),
    "TLR811_3_02": (
        "Dacă A este adevărat, atunci B este adevărat. B NU este adevărat. Este A adevărat?",
        "Dacă A ar face mereu B adevărat, iar B e fals…",
        ["Da", "Nu", "Poate", "Nu putem ști"],
        "Dacă A ar fi adevărat, B ar trebui să fie adevărat. Dar B nu e. Deci A nu poate fi adevărat.",
    ),
    "TLR811_3_03": (
        "Astăzi este miercuri. Ce zi era acum 3 zile?",
        "Numără înapoi: marți, luni, duminică.",
        ["Luni", "Duminică", "Sâmbătă", "Marți"],
        "Miercuri −1 = marți, −2 = luni, −3 = duminică.",
    ),
    "TLR811_3_04": (
        "Dacă înveți, treci testul. Dacă treci testul, primești recompensa. Maya a învățat. Primește Maya recompensa?",
        "Urmează lanțul: învățare → trecere test → recompensă.",
        ["Da", "Nu", "Doar uneori", "Nu putem ști"],
        "Învățare → trecere → recompensă. Maya a învățat, deci primește recompensa.",
    ),
    "TLR811_3_05": (
        "Dacă Anna înoată, poartă ochelari de înot. Anna NU poartă ochelari. Înoată Anna?",
        "Dacă la înot poartă mereu ochelari, iar acum nu poartă…",
        ["Da", "Nu", "Poate", "Doar lunea"],
        "Dacă ar înota, ar purta ochelari. Nu poartă, deci nu înoată.",
    ),
    "TLR811_3_06": (
        "Astăzi este 28 martie. Ce dată este peste 5 zile?",
        "Martie are 31 de zile. Numără înainte de la 28.",
        ["33 martie", "1 aprilie", "2 aprilie", "3 aprilie"],
        "Martie are 31 zile. 28 + 5 = 33. 33 − 31 = 2. Deci este 2 aprilie.",
    ),
    "TLR811_3_07": (
        "Dacă Max mănâncă tort, i se face rău. Max NU i se face rău. A mâncat Max tort?",
        "Dacă tortul îi face mereu rău, iar acum nu i se face…",
        ["Da", "Nu", "Poate", "Doar tort de ciocolată"],
        "Dacă ar fi mâncat tort, i s-ar face rău. Nu i se face, deci nu a mâncat.",
    ),
    "TLR811_3_08": (
        "Dacă A duce la B, B la C, C la D. Se întâmplă A. Se întâmplă D?",
        "Urmează lanțul de la A la D.",
        ["Da", "Nu", "Doar uneori", "Nu putem ști"],
        "A → B → C → D. Dacă A, atunci și D.",
    ),
    "TLR811_3_09": (
        "Este octombrie. Câte luni până în martie (numărând înainte)?",
        "Numără: noiembrie, decembrie, ianuarie, februarie, martie.",
        ["4", "5", "6", "3"],
        "Nov (1), dec (2), ian (3), feb (4), mar (5). Sunt 5 luni.",
    ),
    "TLR811_3_10": (
        "Dacă o formă are 4 laturi egale și 4 unghiuri drepte, este pătrat. Această formă NU are 4 laturi egale. Sigur NU este pătrat?",
        "Poate fi pătrat fără 4 laturi egale?",
        ["Da, nu e pătrat", "Nu, tot ar putea fi pătrat", "Poate", "Doar dacă e mare"],
        "Pătratul trebuie să aibă 4 laturi egale. Dacă nu le are, nu e pătrat.",
    ),
    "TLR811_3_11": (
        "Dacă apeși butonul, lumina se aprinde. Dacă lumina se aprinde, sună clopoțelul. Ai apăsat butonul. Ce se întâmplă?",
        "Urmează lanțul: buton → lumină → clopoțel.",
        ["Nimic", "Doar lumina", "Sună clopoțelul", "Butonul se strică"],
        "Buton → lumină → clopoțel. Ai apăsat, deci sună clopoțelul.",
    ),
    "TLR811_3_12": (
        "Astăzi este vineri. Ce zi va fi peste 10 zile?",
        "10 = 7 + 3. O săptămână întreagă plus 3 zile.",
        ["Duminică", "Luni", "Marți", "Miercuri"],
        "10 zile = 1 săptămână + 3 zile. Vineri + 3 = luni.",
    ),
    "TLR811_3_13": (
        "Toți elevii din clasa A joacă fotbal. Tom NU joacă fotbal. Este Tom în clasa A?",
        "Dacă toți din A joacă fotbal, iar Tom nu…",
        ["Da", "Nu", "Poate", "Doar în weekend"],
        "Toți din A joacă fotbal. Tom nu joacă, deci nu e în clasa A.",
    ),
    "TLR811_3_14": (
        "Dacă ninge, școala e închisă. Dacă școala e închisă, copiii se joacă afară. NU a nins. Putem fi SIGURI că copiii NU se joacă afară?",
        "Școala s-ar putea închide din alt motiv?",
        ["Da, suntem siguri", "Nu, nu putem fi siguri", "Doar vara", "Mereu"],
        "Școala se poate închide și altfel (sărbători, reparații). Copiii tot s-ar putea juca afară.",
    ),
    "TLR811_3_15": (
        "Astăzi este 30 noiembrie. Ce dată este peste 3 zile?",
        "Noiembrie are 30 zile; ce urmează după 30 noiembrie?",
        ["33 noiembrie", "1 decembrie", "2 decembrie", "3 decembrie"],
        "Noiembrie are 30 zile. 30 nov +1 = 1 dec, +2 = 2 dec, +3 = 3 dec.",
    ),
    "TLR811_3_16": (
        "X este mai mare decât Y. Y decât Z. Z decât W. W decât V. Care este cel mai mare?",
        "Cine e în vârful lanțului?",
        ["V", "W", "Y", "X"],
        "X > Y > Z > W > V. X este cel mai mare.",
    ),
    "TLR811_3_17": (
        "Toți peștii pot înota. Ceva nu poate înota. Este pește?",
        "Dacă toți peștii înoată, iar acest lucru nu…",
        ["Da", "Nu", "Poate", "Doar peștii mici"],
        "Toți peștii înoată. Dacă nu poate înota, nu e pește.",
    ),
    "TLR811_3_18": (
        "Astăzi este marți. Ce zi va fi peste 25 zile?",
        "25 ÷ 7 = 3 săptămâni și 4 zile în plus.",
        ["Vineri", "Sâmbătă", "Duminică", "Luni"],
        "25 = 3 săptămâni + 4 zile. Marți + 4 = sâmbătă.",
    ),
    "TLR811_3_19": (
        "Dacă A e adevărat, B trebuie să fie adevărat. Dacă B e adevărat, C trebuie să fie adevărat. C NU este adevărat. Este A adevărat?",
        "Lucrează invers: dacă C e fals, ce e cu B? Apoi cu A?",
        ["Da", "Nu", "Poate", "Nu putem ști"],
        "Dacă A → B → C. C e fals, deci B e fals, deci A e fals.",
    ),
    "TLR811_3_20": (
        "Orice pisică e păroasă. Orice lucru păros e moale. Orice lucru moale e plăcut de îmbrățișat. Mustăți e pisică. E plăcut de îmbrățișat Mustăți?",
        "Urmează lanțul: pisică → păros → moale → plăcut de îmbrățișat.",
        ["Da", "Nu", "Poate", "Doar pisoii"],
        "Pisică → păros → moale → plăcut. Mustăți e pisică, deci e plăcut de îmbrățișat.",
    ),
}
